// Typed loaders for public/data/*.json. Content is data (CLAUDE.md): pages
// render from these, copy changes are JSON edits.

export type UpcomingEvent = {
  title: string;
  dates: string;
  location: string;
  url: string;
  /** Next-race spotlight fields (one entry carries spotlight: true). */
  spotlight?: boolean;
  dates_headline?: string;
  dates_secondary?: string;
  starts_at?: string;
  registration_deadline?: string;
  register_url?: string;
  rules_url?: string;
};

export type PastRace = {
  name: string;
  url: string;
};

export type Partner = {
  name: string;
  website: string;
  image: string;
};

export type NewsItem = {
  title: string;
  platform: string;
  date: string;
  description: string;
  link: string;
  image?: string;
};

export type Testimonial = {
  author: string;
  institution: string;
  image: string;
  quote: string;
};

export type TeamMember = {
  name: string;
  linkedin?: string;
  image: string;
};

export type Publication = {
  id: string;
  title: string;
  authors: string[];
  year: number;
  venue: string;
  venue_short?: string;
  type: string;
  tags: string[];
  featured: boolean;
  status: "published" | "hidden" | string;
  url?: string;
  doi?: string;
  arxiv?: string;
  pdf?: string;
  /** 1200x750 WebP under public/media/research/ (scripts/paper_thumbs.py). */
  thumbnail?: string;
  added?: string;
  source?: string;
  notes?: string;
};

export type PublicationTag = {
  id: string;
  label: string;
  scholar_query?: string;
};

export type PublicationsFile = {
  version: number | string;
  updated: string;
  scholar_query_url: string;
  tags: PublicationTag[];
  items: Publication[];
};

/** id -> label map for rendering tag pills. */
export function tagLabelMap(tags: PublicationTag[]): Record<string, string> {
  return Object.fromEntries(tags.map((t) => [t.id, t.label]));
}

export type TeamHighlight = { event: string; result: string };

export type Team = {
  name: string;
  institution: string;
  country: string;
  website?: string;
  social?: string;
  logo?: string;
  since_year?: number;
  highlights?: TeamHighlight[];
  status: "verify" | "published";
  source?: string;
  /** Square team photo under public/media/team/ (media curator). */
  photo?: string;
};

export type Highlight = {
  id: string;
  type: "image" | "video";
  src: string;
  poster: string;
  caption: string;
  credit: string;
  aspect: "16/9" | "3/2";
  status: "placeholder" | "live";
  /** Event id (icra2026, iv2026, ...) and optional link to its race site. */
  event?: string;
  href?: string;
};

/** public/data/events_map.json (generated by scripts/build-world-map.mjs). */
export type MapEvent = {
  id: string;
  year: number;
  label: string;
  city: string;
  country: string;
  lat: number;
  lng: number;
  x: number;
  y: number;
  kind: "race" | "madgames" | "workshop" | "course" | string;
  status: "held" | "upcoming" | "virtual" | string;
  verified: boolean;
  number?: number;
  source?: string;
  labelDx?: number;
  labelDy?: number;
};

export type MapCountry = {
  iso2: string;
  name: string;
  lat: number;
  lng: number;
  x: number;
  y: number;
  why?: string;
  verified: boolean;
};

export type EventsMap = {
  viewBox: [number, number, number, number];
  projection: string;
  updated: string;
  events: MapEvent[];
  countries: MapCountry[];
};

/** public/data/platform.json: the four pillars with their media panel slot. */
export type PlatformMedia = {
  type: "image" | "video";
  src: string;
  poster: string;
  caption: string;
  credit?: string;
};

export type PlatformRow = {
  id: string;
  n: string;
  title: string;
  body: string;
  href: string;
  linkText: string;
  media: PlatformMedia;
};

/** public/data/community.json (seed values; refreshed by scripts/slack_stats.py). */
export type JoinPhoto = {
  src: string;
  width: number;
  height: number;
  alt: string;
  caption: string;
  credit?: string;
};

/** A community LinkedIn post, re-hosted as a native video (landing v4 section 8). */
export type JoinPost = {
  video: string;
  poster: string;
  width: number;
  height: number;
  author: string;
  author_url?: string;
  post_url: string;
  credit?: string;
  /** One sentence in Cedric's words; never the post text. */
  excerpt?: string;
};

/** YouTube facade: the poster is ours; the embed loads only after a click. */
export type JoinYouTube = {
  poster: string;
  width: number;
  height: number;
  video_id: string;
  title: string;
  channel: string;
  channel_url: string;
  caption: string;
};

export type Community = {
  members: number;
  members_display: string;
  timezones: number;
  continents: number;
  updated: string;
  source: string;
  /** Written by the media curator (landing v4 section 9). */
  join?: {
    photo?: JoinPhoto;
    post?: JoinPost;
    youtube?: JoinYouTube;
  };
};

async function loadJson<T>(name: string): Promise<T> {
  const res = await fetch(`${import.meta.env.BASE_URL}data/${name}`);
  if (!res.ok) throw new Error(`Failed to load ${name}: ${res.status}`);
  return res.json() as Promise<T>;
}

export const loadUpcomingEvents = () => loadJson<UpcomingEvent[]>("upcoming_events.json");
export const loadPastRaces = () => loadJson<PastRace[]>("past_races.json");
export const loadPartners = () => loadJson<Partner[]>("partners.json");
export const loadNews = () => loadJson<NewsItem[]>("news.json");
export const loadTestimonials = () => loadJson<Testimonial[]>("testimonies.json");
export const loadTeamDevelopers = () => loadJson<TeamMember[]>("team_developers.json");
export const loadTeamAlumni = () => loadJson<TeamMember[]>("team_alumni.json");
export const loadPublications = () => loadJson<PublicationsFile>("publications.json");
export const loadTeams = () => loadJson<Team[]>("teams.json");
export const loadHighlights = () => loadJson<Highlight[]>("highlights.json");
export const loadEventsMap = () => loadJson<EventsMap>("events_map.json");
export const loadCommunity = () => loadJson<Community>("community.json");
export const loadPlatform = () => loadJson<PlatformRow[]>("platform.json");

