#!/usr/bin/env python3
"""Thumbnails and figures for the papers in public/data/publications.json.

Two outputs, both WebP under public/media/research/, both logged in docs/media/THUMBS.md
(one row per file; the review column is written by hand and survives re-runs).

1. Thumbnail (default mode): 1200x750 under 120 KB for every featured paper, the
   `thumbnail` field (the /research grid). Strategy per paper (first that works):
     a. arXiv HTML rendering (https://arxiv.org/html/<id>): the first raster <img> inside a
        <figure> (class ltx_figure / ltx_graphics), at least 500x300 px. Recorded as
        "arXiv HTML figure 1". Skipped with --page.
     b. PDF page 1 (the paper's `pdf` field, or https://arxiv.org/pdf/<id>): rasterized with
        pdftoppm at 150 dpi, top 60% kept (title, authors, usually the teaser figure), then
        fitted to 1200x750 biased towards the top. Recorded as "PDF page 1, top 60%".

2. Figure (--size, landing v5): one main figure of the paper at 1600x1000 (16:10, the same
   ratio as the thumbnails) under 200 KB, the `figure` field (the landing research
   carousel shows it next to the abstract). The figure is chosen by hand:
     --figure n      the figure the paper itself numbers n in its arXiv HTML (the caption
                     tag "Figure n:" or "Fig. n:"); --panel k takes the kth graphic inside it
                     (default 1), --panel 2,3 montages panels side by side. SVG graphics
                     (<object> files or inline TikZ/pgfplots) are rasterized with ImageMagick
     --pdf-page p    render page p of the PDF (--dpi, default 300) instead, for papers
                     without arXiv HTML; --pdf-image k takes the page's kth embedded raster
                     at native resolution instead of rendering (pdfimages -list shows them)
     --crop l,t,r,b  keep this box of the source image, fractions 0..1 (cuts captions, side
                     panels, page margins); recorded in the log so the cut is reproducible
     --cover         fill the 16:10 canvas and crop the overflow instead of letterboxing on
                     paper-50
     --no-trim       keep uniform-colour margins (trimmed by default)
   Page-1 crops are thumbnails, never figures: --page is refused together with --size.
   --list prints the figures the arXiv HTML has (number, id, rasters, caption) to pick from.

Usage:
  python3 scripts/paper_thumbs.py [--only id1,id2] [--force] [--page]
  python3 scripts/paper_thumbs.py --list --only id
  python3 scripts/paper_thumbs.py --size 1600 --figure 3 [--panel 1] [--crop l,t,r,b] [--cover] --only id
  python3 scripts/paper_thumbs.py --size 1600 --pdf-page 4 --crop l,t,r,b --only id
  python3 scripts/paper_thumbs.py --size 1600 --pdf-page 5 --pdf-image 1 --only id
  python3 scripts/paper_thumbs.py --size 1600            # figure 1 for every paper with featured_order
Needs: pdftoppm and pdfimages (poppler-utils), Pillow with WebP support, network access;
SVG figures need Playwright's Chromium (pip install playwright; playwright install chromium)
or ImageMagick as a weaker fallback.
"""
from __future__ import annotations

import argparse
import html
import io
import json
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

from PIL import Image, ImageChops, ImageOps

PUBS = Path("public/data/publications.json")
OUT_DIR = Path("public/media/research")
LOG = Path("docs/media/THUMBS.md")
UA = "roboracer-site-thumbs/1.0 (mailto:contact@roboracer.ai)"
MAX_BYTES = 120 * 1024
FIG_MAX_BYTES = 200 * 1024
W, H = 1200, 750
MIN_FIG = (500, 300)
FIG_MIN_WIDTH = 800  # a figure narrower than this is upscaled past 2x at 1600 and goes soft
PAPER = (251, 251, 253)  # --color-paper-50
LICENSE_RE = re.compile(
    r"https?://(?:arxiv\.org/licenses|creativecommons\.org/(?:licenses|publicdomain))/[^\"'\s<>]+"
)
LOG_HEADER = [
    "# Research thumbnails and figures",
    "",
    "Generated by `scripts/paper_thumbs.py`, all under `public/media/research/`, every file",
    "checked by eye after generation (the review column records what was done by hand and",
    "survives re-runs). Credit line on the site: \"Figure: <first author> et al.\"",
    "(PublicationCard).",
    "",
    "- `research-<id>-1200.webp`: 1200x750 WebP under 120 KB, one per featured paper, the",
    "  `thumbnail` field (the /research grid).",
    "- `research-<id>-fig-1600.webp`: 1600x1000 WebP under 200 KB of one main figure of the",
    "  paper, chosen by hand (`--size 1600 --figure n`, or `--pdf-page p --crop l,t,r,b` for",
    "  papers without arXiv HTML), the `figure` field (the landing research carousel).",
    "  Letterboxed on paper-50 unless the source says cover. Never a page-1 crop.",
    "",
    "| id | file | source | license | bytes | review |",
    "|---|---|---|---|---|---|",
]


def fetch(url: str) -> tuple[bytes, str]:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        return r.read(), r.geturl()


def arxiv_id(p: dict) -> str | None:
    a = p.get("arxiv")
    if a:
        return str(a).replace("arXiv:", "").strip()
    for field in ("url", "pdf"):
        m = re.search(r"arxiv\.org/(?:abs|pdf|html)/(\d{4}\.\d{4,5})(v\d+)?", p.get(field) or "")
        if m:
            return m.group(1)
    return None


def arxiv_license(aid: str) -> str:
    """License link shown on the arXiv abstract page (nonexclusive-distrib or a CC link)."""
    try:
        page, _ = fetch(f"https://arxiv.org/abs/{aid}")
    except Exception as e:  # noqa: BLE001
        print(f"  abs page unavailable ({e})")
        return "arXiv (license not read)"
    m = LICENSE_RE.search(page.decode("utf-8", "replace"))
    return m.group(0) if m else "arXiv (no license link found)"


def first_figure_url(aid: str) -> str | None:
    try:
        raw, final = fetch(f"https://arxiv.org/html/{aid}")
    except Exception as e:  # noqa: BLE001
        print(f"  arxiv html unavailable ({e})")
        return None
    page = raw.decode("utf-8", "replace")
    # Figures first; fall back to any ltx_graphics image. Image paths are relative to
    # the page URL the way a browser resolves them (the page lives at /html/<id> and
    # references "<id>v1/x1.png"), so join, never append.
    for pat in (
        r'<figure[^>]*class="[^"]*ltx_figure[^"]*"[^>]*>.*?<img[^>]+src="([^"]+)"',
        r'<img[^>]+class="[^"]*ltx_graphics[^"]*"[^>]+src="([^"]+)"',
    ):
        m = re.search(pat, page, re.S)
        if m:
            return urllib.parse.urljoin(final, html.unescape(m.group(1)))
    return None


class _Figures(HTMLParser):
    """Every <figure> of an arXiv HTML page in document order: id, classes, the graphics inside
    it (nested panels included) and the text of its own <figcaption>. Graphics are ltx_graphics
    rasters, <object type="image/svg+xml"> files, or inline <svg> (TikZ/pgfplots); the last two
    carry svg=True and are rasterized with ImageMagick when picked."""

    def __init__(self, raw: str) -> None:
        super().__init__(convert_charrefs=True)
        self.raw = raw
        self._line_starts = [0] + [i + 1 for i, ch in enumerate(raw) if ch == "\n"]
        self.figures: list[dict] = []
        self._open: list[int] = []
        self._caption_of: int | None = None
        self._svg_start: int | None = None
        self._svg_size = ("?", "?")
        self._svg_depth = 0

    def _offset(self) -> int:
        line, col = self.getpos()
        return self._line_starts[line - 1] + col

    def _add_graphic(self, img: dict) -> None:
        for i in self._open:
            self.figures[i]["imgs"].append(img)

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        a = dict(attrs)
        cls = (a.get("class") or "").split()
        if tag == "figure":
            self.figures.append(
                {"id": a.get("id") or "", "panel": "ltx_figure_panel" in cls, "table": "ltx_table" in cls, "imgs": [], "caption": ""}
            )
            self._open.append(len(self.figures) - 1)
        elif tag == "img" and "ltx_graphics" in cls and self._open:
            self._add_graphic({"src": a.get("src") or "", "w": a.get("width") or "?", "h": a.get("height") or "?", "svg": False})
        elif tag == "object" and self._open and "svg" in (a.get("type") or ""):
            self._add_graphic({"src": a.get("data") or "", "w": a.get("width") or "?", "h": a.get("height") or "?", "svg": True})
        elif tag == "svg" and self._open:
            if self._svg_depth == 0:
                self._svg_start = self._offset()
                self._svg_size = (a.get("width") or "?", a.get("height") or "?")
            self._svg_depth += 1
        elif tag == "figcaption" and self._open:
            self._caption_of = self._open[-1]

    def handle_endtag(self, tag: str) -> None:
        if tag == "figure" and self._open:
            self._open.pop()
        elif tag == "svg" and self._svg_depth:
            self._svg_depth -= 1
            if self._svg_depth == 0 and self._open and self._svg_start is not None:
                end = self._offset() + len("</svg>")
                w, h = self._svg_size
                self._add_graphic({"src": f"inline-svg@{self._svg_start}", "w": w, "h": h, "svg": True, "markup": self.raw[self._svg_start:end]})
                self._svg_start = None
        elif tag == "figcaption":
            self._caption_of = None

    def handle_data(self, data: str) -> None:
        if self._caption_of is not None:
            self.figures[self._caption_of]["caption"] += data


def arxiv_figures(aid: str) -> list[dict] | None:
    """The numbered figures of the arXiv HTML rendering: {number, id, imgs[{src, url, w, h}],
    caption}. Numbering follows the paper's own caption tags ("Figure 9:"), not the element
    ids, so minipage panels that carry their own number count as figures; tables never do."""
    try:
        raw, final = fetch(f"https://arxiv.org/html/{aid}")
    except Exception as e:  # noqa: BLE001
        print(f"  arxiv html unavailable ({e})")
        return None
    parser = _Figures(raw.decode("utf-8", "replace"))
    parser.feed(parser.raw)
    out: list[dict] = []
    for f in parser.figures:
        # "Figure 3:" (most classes) or "Fig. 3:" (IEEEtran); tables are "Table n".
        m = re.match(r"\s*(?:Figure|Fig\.?)\s*(\d+)", f["caption"], re.I)
        if f["table"] or not m:
            continue
        caption = re.sub(r"^(?:Figure|Fig\.?)\s*\d+\s*[:.]?\s*", "", re.sub(r"\s+", " ", f["caption"]).strip(), flags=re.I)
        imgs, seen = [], set()
        for im in f["imgs"]:
            if im["src"] and im["src"] not in seen:
                seen.add(im["src"])
                url = None if "markup" in im else urllib.parse.urljoin(final, html.unescape(im["src"]))
                imgs.append({**im, "url": url})
        out.append({"number": int(m.group(1)), "id": f["id"], "imgs": imgs, "caption": caption})
    return out


def print_figures(aid: str) -> None:
    figs = arxiv_figures(aid)
    if figs is None:
        return
    print(f"  arXiv HTML {aid}: {len(figs)} numbered figures")
    for f in figs:
        graphics = ", ".join(
            f"{'inline svg' if 'markup' in i else Path(i['src']).name}{' (svg)' if i['svg'] and 'markup' not in i else ''} {i['w']}x{i['h']}"
            for i in f["imgs"]
        ) or "no graphic"
        print(f"  Figure {f['number']:>2}  {f['id']:<12} {graphics}")
        print(f"             {f['caption'][:140]}")


def rasterize_svg(markup: bytes, tmp: Path, dpi: int = 300) -> Image.Image | None:
    """Chromium (Playwright, the webapp-testing dependency) renders the SVG at dpi/96 device
    pixels per CSS pixel on white. ImageMagick is the fallback: its internal renderer drops
    the <use> glyphs LaTeXML emits, so text and sometimes whole diagrams come out blank."""
    svg, png = tmp / "fig.svg", tmp / "fig.png"
    svg.write_bytes(markup)
    png.unlink(missing_ok=True)
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        sync_playwright = None
    if sync_playwright is not None:
        try:
            with sync_playwright() as pw:
                browser = pw.chromium.launch()
                page = browser.new_page(device_scale_factor=dpi / 96)
                page.goto(svg.resolve().as_uri())
                page.locator("svg").first.screenshot(path=str(png), omit_background=False)
                browser.close()
        except Exception as e:  # noqa: BLE001
            print(f"  chromium svg render failed ({str(e)[:120]}); trying ImageMagick")
    if not png.exists():
        r = subprocess.run(
            ["convert", "-density", str(dpi), "-background", "white", str(svg), "-flatten", str(png)], capture_output=True
        )
        if r.returncode != 0 or not png.exists():
            err = r.stderr.decode("utf-8", "replace").strip().splitlines()
            print(f"  svg rasterization failed ({err[0][:120] if err else 'is ImageMagick installed?'})")
            return None
    img = Image.open(png)
    img.load()
    if img.convert("L").getextrema()[0] == 255:
        print("  svg rendered blank")
        return None
    return img


def graphic_image(entry: dict, tmp: Path, dpi: int = 300) -> Image.Image | None:
    """One figure graphic as a Pillow image: raster as is, SVG (file or inline) rasterized."""
    if "markup" in entry:
        return rasterize_svg(entry["markup"].encode("utf-8"), tmp, dpi)
    try:
        raw, _ = fetch(entry["url"])
    except Exception as e:  # noqa: BLE001
        print(f"  figure fetch failed ({e})")
        return None
    return rasterize_svg(raw, tmp, dpi) if entry["svg"] else load_image(raw)


def montage(imgs: list[Image.Image], gap: float = 0.02) -> Image.Image:
    """Panels side by side at a common height, a 2% gap of paper between them."""
    if len(imgs) == 1:
        return imgs[0]
    h = max(i.height for i in imgs)
    scaled = [i.resize((round(i.width * h / i.height), h), Image.LANCZOS) for i in imgs]
    g = round(h * gap)
    out = Image.new("RGB", (sum(i.width for i in scaled) + g * (len(scaled) - 1), h), PAPER)
    x = 0
    for i in scaled:
        out.paste(i, (x, 0))
        x += i.width + g
    return out


def figure_image(aid: str, number: int, panels: list[int], tmp: Path, dpi: int = 300) -> tuple[Image.Image, str] | None:
    """Figure `number` of the arXiv HTML, the listed panels montaged left to right."""
    figs = arxiv_figures(aid)
    if not figs:
        print("  no numbered figures in the arXiv HTML")
        return None
    fig = next((f for f in figs if f["number"] == number), None)
    if fig is None:
        print(f"  no figure {number} (the HTML has {[f['number'] for f in figs]})")
        return None
    parts, names = [], []
    for k in panels:
        if k < 1 or k > len(fig["imgs"]):
            print(f"  figure {number} has {len(fig['imgs'])} graphics, no panel {k}")
            return None
        entry = fig["imgs"][k - 1]
        img = graphic_image(entry, tmp, dpi)
        if img is None:
            return None
        name = "inline svg" if "markup" in entry else Path(entry["src"]).name
        print(f"  figure {number} panel {k}: {name} {img.width}x{img.height}")
        parts.append(flatten(img))
        names.append(entry["url"] or f"{entry['src']} of https://arxiv.org/html/{aid}")
    return montage(parts), ", ".join(names)


def load_image(data: bytes) -> Image.Image | None:
    try:
        img = Image.open(io.BytesIO(data))
        img.load()
        return img
    except Exception as e:  # noqa: BLE001
        print(f"  not a raster image ({e})")
        return None


def flatten(img: Image.Image) -> Image.Image:
    """Alpha onto paper-50, everything to RGB."""
    if img.mode in ("RGBA", "LA") or (img.mode == "P" and "transparency" in img.info):
        img = img.convert("RGBA")
        bg = Image.new("RGB", img.size, PAPER)
        bg.paste(img, mask=img.split()[-1])
        return bg
    return img.convert("RGB")


def compose(img: Image.Image, mode: str) -> Image.Image:
    """figure: cover-crop when the aspect is near 16/10, else letterbox on paper;
    page: cover-crop biased to the top so the title block survives."""
    img = flatten(img)
    if mode == "page":
        return ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.3))
    aspect = img.width / img.height
    if 1.25 <= aspect <= 2.0:
        return ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.5))
    inner = ImageOps.contain(img, (W - 48, H - 48), Image.LANCZOS)
    canvas = Image.new("RGB", (W, H), PAPER)
    canvas.paste(inner, ((W - inner.width) // 2, (H - inner.height) // 2))
    return canvas


def save_webp(img: Image.Image, out: Path, max_bytes: int) -> bool:
    for q in (82, 74, 66, 58, 50, 42, 34):
        img.save(out, "WEBP", quality=q, method=6)
        if out.stat().st_size <= max_bytes:
            return True
    return out.exists()


def to_webp(img: Image.Image, out: Path, mode: str) -> bool:
    if mode == "figure" and (img.width < MIN_FIG[0] or img.height < MIN_FIG[1]):
        print(f"  figure too small ({img.width}x{img.height}), skipping")
        return False
    return save_webp(compose(img, mode), out, MAX_BYTES)


def parse_crop(s: str) -> tuple[float, float, float, float]:
    try:
        l, t, r, b = (float(x) for x in s.split(","))
    except ValueError:
        raise SystemExit("--crop wants l,t,r,b as fractions of the source image, e.g. 0,0.1,1,0.8")
    if not (0 <= l < r <= 1 and 0 <= t < b <= 1):
        raise SystemExit("--crop fractions must satisfy 0 <= l < r <= 1 and 0 <= t < b <= 1")
    return l, t, r, b


def crop_box(img: Image.Image, box: tuple[float, float, float, float]) -> Image.Image:
    l, t, r, b = box
    return img.crop((round(l * img.width), round(t * img.height), round(r * img.width), round(b * img.height)))


def trim(img: Image.Image, tol: int = 16, pad: float = 0.015) -> Image.Image:
    """Cut uniform margins (the colour of the top-left pixel: white or paper for nearly every
    figure), keeping a 1.5% breathing margin. JPEG noise is below the tolerance."""
    bg = Image.new("RGB", img.size, img.getpixel((0, 0)))
    mask = ImageChops.difference(img, bg).convert("L").point(lambda v: 255 if v > tol else 0)
    bbox = mask.getbbox()
    if not bbox:
        return img
    px, py = round(img.width * pad), round(img.height * pad)
    return img.crop((max(0, bbox[0] - px), max(0, bbox[1] - py), min(img.width, bbox[2] + px), min(img.height, bbox[3] + py)))


def compose_figure(img: Image.Image, size: int, cover: bool) -> Image.Image:
    """16:10 canvas `size` wide: cover-crop on request, otherwise contain on paper-50 with a
    2% margin (figures keep their aspect; the carousel gets one fixed box)."""
    w, h = size, round(size * 10 / 16)
    if cover:
        return ImageOps.fit(img, (w, h), Image.LANCZOS, centering=(0.5, 0.5))
    m = round(size * 0.02)
    inner = ImageOps.contain(img, (w - 2 * m, h - 2 * m), Image.LANCZOS)
    canvas = Image.new("RGB", (w, h), PAPER)
    canvas.paste(inner, ((w - inner.width) // 2, (h - inner.height) // 2))
    return canvas


def download_pdf(pdf_url: str, tmp: Path) -> Path | None:
    try:
        data, _ = fetch(pdf_url)
    except Exception as e:  # noqa: BLE001
        print(f"  pdf unavailable ({e})")
        return None
    if not data.startswith(b"%PDF"):
        print("  pdf url did not return a PDF")
        return None
    pdf = tmp / "paper.pdf"
    pdf.write_bytes(data)
    return pdf


def pdf_embedded_image(pdf_url: str, page: int, k: int, tmp: Path) -> Image.Image | None:
    """The kth raster pdfimages extracts from `page` (1-based, content order; soft masks count
    as entries, `pdfimages -list` shows them). Native resolution, unlike a page render."""
    pdf = download_pdf(pdf_url, tmp)
    if pdf is None:
        return None
    r = subprocess.run(
        ["pdfimages", "-png", "-f", str(page), "-l", str(page), str(pdf), str(tmp / "emb")], capture_output=True
    )
    files = sorted(tmp.glob("emb-*.png"))
    if r.returncode != 0 or not files:
        print(f"  pdfimages found nothing on page {page}")
        return None
    if k < 1 or k > len(files):
        print(f"  page {page} has {len(files)} embedded images, no image {k}")
        return None
    img = Image.open(files[k - 1])
    img.load()
    return img


def render_pdf(pdf_url: str, page: int, dpi: int, tmp: Path) -> Image.Image | None:
    pdf = download_pdf(pdf_url, tmp)
    if pdf is None:
        return None
    r = subprocess.run(
        ["pdftoppm", "-f", str(page), "-l", str(page), "-r", str(dpi), "-png", str(pdf), str(tmp / "p")],
        capture_output=True,
    )
    pngs = sorted(tmp.glob("p*.png"))
    if r.returncode != 0 or not pngs:
        print(f"  pdftoppm failed for page {page}")
        return None
    img = Image.open(pngs[0])
    img.load()
    return img


def pdf_page1(pdf_url: str, tmp: Path) -> Image.Image | None:
    page = render_pdf(pdf_url, 1, 150, tmp)
    if page is None:
        return None
    # Top 60% of the page: title block and, for most papers, the teaser figure.
    return page.crop((0, 0, page.width, int(page.height * 0.6)))


def upsert_log(rows: dict[str, tuple[str, str, str, str, int]], order: list[str]) -> None:
    """rows: file (or id when there is no file) -> (id, file, source, license, bytes). One row
    per file, so a paper's thumbnail and figure are two rows. Existing review notes are kept."""
    existing: dict[str, list[str]] = {}
    if LOG.exists():
        for line in LOG.read_text().splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) == 6 and cells[0] not in ("id", "---"):
                existing[cells[1] or cells[0]] = cells
    for key, (pid, file, source, lic, size) in rows.items():
        review = existing.get(key, [""] * 6)[5]
        existing[key] = [pid, file, source, lic, str(size), review]
    rank = {pid: i for i, pid in enumerate(order)}

    def sort_key(key: str) -> tuple[int, bool, str]:
        cells = existing[key]
        return (rank.get(cells[0], len(rank)), "-fig-" in cells[1], cells[1])

    lines = LOG_HEADER + ["| " + " | ".join(existing[k]) + " |" for k in sorted(existing, key=sort_key)]
    LOG.write_text("\n".join(lines) + "\n")


def make_thumbnail(p: dict, args: argparse.Namespace, rows: dict) -> None:
    out = OUT_DIR / f"research-{p['id']}-1200.webp"
    if out.exists() and not args.force:
        print(f"{p['id']}: exists")
        return
    print(f"{p['id']}: {p['title'][:70]}")
    aid = arxiv_id(p)
    source = lic = None
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        if aid and not args.page:
            fig = first_figure_url(aid)
            if fig:
                try:
                    raw, _ = fetch(fig)
                    img = load_image(raw)
                    if img and to_webp(img, out, "figure"):
                        source, lic = f"arXiv HTML figure 1: {fig}", arxiv_license(aid)
                except Exception as e:  # noqa: BLE001
                    print(f"  figure fetch failed ({e})")
        if not source:
            pdf_url = p.get("pdf") or (f"https://arxiv.org/pdf/{aid}" if aid else None)
            if pdf_url:
                page = pdf_page1(pdf_url, tmp)
                if page and to_webp(page, out, "page"):
                    source = f"PDF page 1, top 60%: {pdf_url}"
                    lic = arxiv_license(aid) if aid else "publisher PDF page render, attribution; remove on request"
    if source:
        p["thumbnail"] = f"/media/research/{out.name}"
        rows[out.name] = (p["id"], out.name, source, lic or "", out.stat().st_size)
        print(f"  ok <- {source} ({out.stat().st_size // 1024} KB)")
    else:
        if not out.exists():
            p.pop("thumbnail", None)
        rows[p["id"]] = (p["id"], "", "NONE - needs a manual image", "", 0)
        print("  no thumbnail")


def make_figure(p: dict, args: argparse.Namespace, rows: dict) -> None:
    out = OUT_DIR / f"research-{p['id']}-fig-{args.size}.webp"
    if out.exists() and not args.force:
        print(f"{p['id']}: figure exists")
        return
    print(f"{p['id']}: {p['title'][:70]}")
    aid = arxiv_id(p)
    crop = parse_crop(args.crop) if args.crop else None
    crop_note = ", crop ({:.3f},{:.3f},{:.3f},{:.3f})".format(*crop) if crop else ""
    img = source = lic = None
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        if args.pdf_page:
            pdf_url = p.get("pdf") or (f"https://arxiv.org/pdf/{aid}" if aid else None)
            if not pdf_url:
                print("  no pdf url")
                return
            if args.pdf_image:
                img = pdf_embedded_image(pdf_url, args.pdf_page, args.pdf_image, tmp)
                if img is not None:
                    print(f"  page {args.pdf_page} embedded image {args.pdf_image}: {img.width}x{img.height}")
                    source = f"PDF page {args.pdf_page} embedded image {args.pdf_image}{crop_note}: {pdf_url}"
            else:
                img = render_pdf(pdf_url, args.pdf_page, args.dpi, tmp)
                if img is not None:
                    print(f"  page {args.pdf_page} rendered {img.width}x{img.height}")
                    source = f"PDF page {args.pdf_page} at {args.dpi} dpi{crop_note}: {pdf_url}"
            if img is not None:
                lic = arxiv_license(aid) if aid else "publisher PDF figure render, attribution; remove on request"
        elif not aid:
            print("  no arXiv id: use --pdf-page p --crop l,t,r,b")
            return
        else:
            n = args.figure or 1
            panels = [int(x) for x in str(args.panel).split(",") if x.strip()]
            got = figure_image(aid, n, panels, tmp, args.dpi)
            if got:
                img, urls = got
                panel = "" if panels == [1] else f" panel{'s' if len(panels) > 1 else ''} {','.join(map(str, panels))}"
                source = f"arXiv HTML figure {n}{panel}{crop_note}: {urls}"
                lic = arxiv_license(aid)
    if img is None or source is None:
        print("  no figure")
        return
    img = flatten(img)
    if crop:
        img = crop_box(img, crop)
    if not args.no_trim:
        img = trim(img)
    print(f"  after crop/trim: {img.width}x{img.height}")
    if img.width < FIG_MIN_WIDTH:
        print(f"  warning: source narrower than {FIG_MIN_WIDTH} px, the 1600 render will be soft")
    save_webp(compose_figure(img, args.size, args.cover), out, FIG_MAX_BYTES)
    if args.cover:
        source += " (cover)"
    p["figure"] = f"/media/research/{out.name}"
    rows[out.name] = (p["id"], out.name, source, lic or "", out.stat().st_size)
    print(f"  ok <- {source} ({out.stat().st_size // 1024} KB)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--page", action="store_true", help="thumbnail: skip the arXiv figure, use the page-1 crop")
    ap.add_argument("--list", action="store_true", help="print the numbered figures of the arXiv HTML")
    ap.add_argument("--size", type=int, default=0, help="figure mode: width of the 16:10 figure WebP (1600)")
    ap.add_argument("--figure", type=int, default=0, help="figure mode: the paper's figure number (default 1)")
    ap.add_argument("--panel", default="1", help="figure mode: which graphic(s) inside the figure, e.g. 2 or 2,3 (montaged)")
    ap.add_argument("--pdf-page", type=int, default=0, help="figure mode: render this PDF page instead")
    ap.add_argument("--pdf-image", type=int, default=0, help="figure mode: with --pdf-page, take its kth embedded raster at native size")
    ap.add_argument("--dpi", type=int, default=300, help="figure mode: PDF page and SVG render resolution")
    ap.add_argument("--crop", default="", help="figure mode: l,t,r,b fractions of the source to keep")
    ap.add_argument("--cover", action="store_true", help="figure mode: fill the canvas instead of letterboxing")
    ap.add_argument("--no-trim", action="store_true", help="figure mode: keep uniform margins")
    args = ap.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()}
    figure_mode = bool(args.size or args.figure or args.pdf_page or args.crop or args.cover)
    if figure_mode and args.page:
        raise SystemExit("--page makes thumbnails; a page-1 crop is never a figure")
    if figure_mode and not args.size:
        args.size = 1600
    if figure_mode and (args.figure or args.pdf_page or args.crop) and len(only) != 1:
        raise SystemExit("--figure/--pdf-page/--crop describe one paper: pass exactly one id with --only")

    data = json.loads(PUBS.read_text())
    items = data["items"]
    if args.list:
        for p in items:
            if only and p["id"] not in only:
                continue
            aid = arxiv_id(p)
            print(f"{p['id']}: {p['title'][:70]}")
            if aid:
                print_figures(aid)
            else:
                print("  no arXiv id")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    LOG.parent.mkdir(parents=True, exist_ok=True)
    rows: dict[str, tuple[str, str, str, str, int]] = {}
    for p in items:
        if only:
            if p["id"] not in only:
                continue
        elif figure_mode:
            if not p.get("featured_order"):
                continue
        elif not p.get("featured") or p.get("status") != "published":
            continue
        if figure_mode:
            make_figure(p, args, rows)
        else:
            make_thumbnail(p, args, rows)

    PUBS.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    upsert_log(rows, [p["id"] for p in items])
    print(f"updated {PUBS}; log in {LOG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
