#!/usr/bin/env python3
"""Make a 1200x750 WebP thumbnail for every featured paper and fill `thumbnail` in
public/data/publications.json.

Strategy per paper (first that works):
  1. arXiv HTML rendering (https://arxiv.org/html/<id>): the first raster <img> inside a
     <figure> (class ltx_figure / ltx_graphics), at least 500x300 px. Best-looking and the
     figure the authors chose first. Recorded as "arXiv HTML figure 1". Skipped with --page.
  2. PDF page 1 (the paper's `pdf` field, or https://arxiv.org/pdf/<id>): rasterized with
     pdftoppm at 150 dpi, top 60% kept (title, authors, usually the teaser figure), then
     fitted to 1200x750 biased towards the top. Recorded as "PDF page 1, top 60%".
Output: public/media/research/research-<id>-1200.webp (under 120 KB, quality stepped
down until it fits; Pillow, because neither cwebp nor ImageMagick 7 exist on this machine)
and one upserted row per id in docs/media/THUMBS.md (file, source, license, bytes; the
"review" column is written by hand after looking at every file and is preserved on re-runs).

Usage: python3 scripts/paper_thumbs.py [--only id1,id2] [--force] [--page]
  --page  skip the arXiv figure and use the page-1 crop (for figures that turned out to be
          a logo, a blank page, or a wall of text)
Needs: pdftoppm (poppler-utils), Pillow with WebP support, network access.
"""
from __future__ import annotations

import argparse
import html
import io
import json
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

from PIL import Image, ImageOps

PUBS = Path("public/data/publications.json")
OUT_DIR = Path("public/media/research")
LOG = Path("docs/media/THUMBS.md")
UA = "roboracer-site-thumbs/1.0 (mailto:contact@roboracer.ai)"
MAX_BYTES = 120 * 1024
W, H = 1200, 750
MIN_FIG = (500, 300)
PAPER = (251, 251, 253)  # --color-paper-50
LICENSE_RE = re.compile(
    r"https?://(?:arxiv\.org/licenses|creativecommons\.org/(?:licenses|publicdomain))/[^\"'\s<>]+"
)
LOG_HEADER = [
    "# Research thumbnails",
    "",
    "Generated by `scripts/paper_thumbs.py`: 1200x750 WebP under 120 KB in",
    "`public/media/research/`, one per featured paper, `thumbnail` filled in",
    "`public/data/publications.json`. Every file is checked by eye after generation; the",
    "review column records what was done by hand. Credit line on the site: \"Figure: <first",
    "author> et al.\" (PublicationCard).",
    "",
    "| id | file | source | license | bytes | review |",
    "|---|---|---|---|---|---|",
]


def fetch(url: str) -> tuple[bytes, str]:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=45) as r:
        return r.read(), r.geturl()


def arxiv_id(p: dict) -> str | None:
    a = p.get("arxiv")
    if a:
        return str(a).replace("arXiv:", "").strip()
    for field in ("url", "pdf"):
        m = re.search(r"arxiv\.org/(?:abs|pdf|html)/(\d{4}\.\d{4,5})(v\d+)?", p.get(field) or "")
        if m:
            return m.group(1)
    return None


def arxiv_license(aid: str) -> str:
    """License link shown on the arXiv abstract page (nonexclusive-distrib or a CC link)."""
    try:
        page, _ = fetch(f"https://arxiv.org/abs/{aid}")
    except Exception as e:  # noqa: BLE001
        print(f"  abs page unavailable ({e})")
        return "arXiv (license not read)"
    m = LICENSE_RE.search(page.decode("utf-8", "replace"))
    return m.group(0) if m else "arXiv (no license link found)"


def first_figure_url(aid: str) -> str | None:
    try:
        raw, final = fetch(f"https://arxiv.org/html/{aid}")
    except Exception as e:  # noqa: BLE001
        print(f"  arxiv html unavailable ({e})")
        return None
    page = raw.decode("utf-8", "replace")
    # Figures first; fall back to any ltx_graphics image. Image paths are relative to
    # the page URL the way a browser resolves them (the page lives at /html/<id> and
    # references "<id>v1/x1.png"), so join, never append.
    for pat in (
        r'<figure[^>]*class="[^"]*ltx_figure[^"]*"[^>]*>.*?<img[^>]+src="([^"]+)"',
        r'<img[^>]+class="[^"]*ltx_graphics[^"]*"[^>]+src="([^"]+)"',
    ):
        m = re.search(pat, page, re.S)
        if m:
            return urllib.parse.urljoin(final, html.unescape(m.group(1)))
    return None


def load_image(data: bytes) -> Image.Image | None:
    try:
        img = Image.open(io.BytesIO(data))
        img.load()
        return img
    except Exception as e:  # noqa: BLE001
        print(f"  not a raster image ({e})")
        return None


def flatten(img: Image.Image) -> Image.Image:
    """Alpha onto paper-50, everything to RGB."""
    if img.mode in ("RGBA", "LA") or (img.mode == "P" and "transparency" in img.info):
        img = img.convert("RGBA")
        bg = Image.new("RGB", img.size, PAPER)
        bg.paste(img, mask=img.split()[-1])
        return bg
    return img.convert("RGB")


def compose(img: Image.Image, mode: str) -> Image.Image:
    """figure: cover-crop when the aspect is near 16/10, else letterbox on paper;
    page: cover-crop biased to the top so the title block survives."""
    img = flatten(img)
    if mode == "page":
        return ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.3))
    aspect = img.width / img.height
    if 1.25 <= aspect <= 2.0:
        return ImageOps.fit(img, (W, H), Image.LANCZOS, centering=(0.5, 0.5))
    inner = ImageOps.contain(img, (W - 48, H - 48), Image.LANCZOS)
    canvas = Image.new("RGB", (W, H), PAPER)
    canvas.paste(inner, ((W - inner.width) // 2, (H - inner.height) // 2))
    return canvas


def to_webp(img: Image.Image, out: Path, mode: str) -> bool:
    if mode == "figure" and (img.width < MIN_FIG[0] or img.height < MIN_FIG[1]):
        print(f"  figure too small ({img.width}x{img.height}), skipping")
        return False
    final = compose(img, mode)
    for q in (82, 74, 66, 58, 50, 42, 34):
        final.save(out, "WEBP", quality=q, method=6)
        if out.stat().st_size <= MAX_BYTES:
            return True
    return out.exists()


def pdf_page1(pdf_url: str, tmp: Path) -> Image.Image | None:
    try:
        data, _ = fetch(pdf_url)
    except Exception as e:  # noqa: BLE001
        print(f"  pdf unavailable ({e})")
        return None
    if not data.startswith(b"%PDF"):
        print("  pdf url did not return a PDF")
        return None
    pdf = tmp / "paper.pdf"
    pdf.write_bytes(data)
    r = subprocess.run(
        ["pdftoppm", "-f", "1", "-l", "1", "-r", "150", "-png", str(pdf), str(tmp / "p")],
        capture_output=True,
    )
    pngs = sorted(tmp.glob("p*.png"))
    if r.returncode != 0 or not pngs:
        print("  pdftoppm failed")
        return None
    page = Image.open(pngs[0])
    page.load()
    # Top 60% of the page: title block and, for most papers, the teaser figure.
    return page.crop((0, 0, page.width, int(page.height * 0.6)))


def upsert_log(rows: dict[str, tuple[str, str, str, int]], order: list[str]) -> None:
    """rows: id -> (file, source, license, bytes). Existing review notes are kept."""
    existing: dict[str, list[str]] = {}
    if LOG.exists():
        for line in LOG.read_text().splitlines():
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) == 6 and cells[0] not in ("id", "---"):
                existing[cells[0]] = cells
    for pid, (file, source, lic, size) in rows.items():
        review = existing.get(pid, [""] * 6)[5]
        existing[pid] = [pid, file, source, lic, str(size), review]
    rank = {pid: i for i, pid in enumerate(order)}
    ids = sorted(existing, key=lambda k: rank.get(k, len(rank)))
    lines = LOG_HEADER + ["| " + " | ".join(existing[k]) + " |" for k in ids]
    LOG.write_text("\n".join(lines) + "\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default="")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--page", action="store_true", help="skip the arXiv figure, use the page-1 crop")
    args = ap.parse_args()
    only = {s.strip() for s in args.only.split(",") if s.strip()}

    data = json.loads(PUBS.read_text())
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    LOG.parent.mkdir(parents=True, exist_ok=True)
    rows: dict[str, tuple[str, str, str, int]] = {}
    for p in data["items"]:
        if not p.get("featured") or p.get("status") != "published" or (only and p["id"] not in only):
            continue
        out = OUT_DIR / f"research-{p['id']}-1200.webp"
        if out.exists() and not args.force:
            print(f"{p['id']}: exists")
            continue
        print(f"{p['id']}: {p['title'][:70]}")
        aid = arxiv_id(p)
        source = lic = None
        with tempfile.TemporaryDirectory() as td:
            tmp = Path(td)
            if aid and not args.page:
                fig = first_figure_url(aid)
                if fig:
                    try:
                        raw, _ = fetch(fig)
                        img = load_image(raw)
                        if img and to_webp(img, out, "figure"):
                            source, lic = f"arXiv HTML figure 1: {fig}", arxiv_license(aid)
                    except Exception as e:  # noqa: BLE001
                        print(f"  figure fetch failed ({e})")
            if not source:
                pdf_url = p.get("pdf") or (f"https://arxiv.org/pdf/{aid}" if aid else None)
                if pdf_url:
                    page = pdf_page1(pdf_url, tmp)
                    if page and to_webp(page, out, "page"):
                        source = f"PDF page 1, top 60%: {pdf_url}"
                        lic = arxiv_license(aid) if aid else "publisher PDF page render, attribution; remove on request"
        if source:
            p["thumbnail"] = f"/media/research/{out.name}"
            rows[p["id"]] = (out.name, source, lic or "", out.stat().st_size)
            print(f"  ok <- {source} ({out.stat().st_size // 1024} KB)")
        else:
            if not out.exists():
                p.pop("thumbnail", None)
            rows[p["id"]] = ("", "NONE - needs a manual image", "", 0)
            print("  no thumbnail")

    PUBS.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
    upsert_log(rows, [p["id"] for p in data["items"]])
    print(f"updated {PUBS}; log in {LOG}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
