name: Build & Deploy (Vite -> gh-pages)

on:
  push:
    branches: [ main ]   # or your default branch
  workflow_dispatch: {}

permissions:
  contents: write  # needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: SPA fallback (404 -> index)
        # Ensures client-side routing works on refresh
        run: |
          cp dist/index.html dist/404.html || true

      - name: Disable Jekyll
        # Prevents GitHub Pages from ignoring files/folders starting with underscore
        run: |
          touch dist/.nojekyll

      # Optional: Set a custom domain
      # - name: Add CNAME
      #   run: echo "www.example.com" > dist/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # If you want to keep commit history on gh-pages:
          # keep_files: true
          # commit_message: 'deploy: ${{ github.sha }}'
