import { createRef, useEffect, useId, useMemo, useRef, useState, type CSSProperties, type RefObject } from "react";
import { loadEventsMap, type EventsMap, type MapEvent, type MapRegion } from "../../lib/data";
import { gsap, useGSAP, useDesktop, DESKTOP_QUERY, EASE_OUT_EXPO, MOTION_OK_QUERY, ScrollTrigger } from "../../lib/motion";
import { usePrefersReducedMotion } from "../../hooks/usePrefersReducedMotion";
import StatTicker, { type StatTickerHandle } from "./StatTicker";
// Generated by scripts/build-world-map.mjs (Natural Earth I, 1600 wide, height
// fitted to the land). Inlined so the land path, the regions and the pins share
// one coordinate space.
import worldLandSvg from "../../../public/media/map/world-land.svg?raw";

const LAND_PATH = /\sd="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "";
const VIEWBOX = /viewBox="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "0 0 1600 706";
const [, , VB_W, VB_H] = VIEWBOX.split(" ").map(Number);

// Paper chapter (Cedric, 2026-08-22): the land-fitted viewBox, no overlay
// frame; the header sits above the map, the counters and the legend below.
// Base state before the reveal: continents as hairline slate outlines on
// paper, no fill, no labels, no pins.
const LAND_STROKE = "#1e3a48";
const ASPECT = VB_W / VB_H;
// Everything around the map inside the pinned viewport (nav 85, header row,
// gaps, counters row, paddings) at md and up; the map is capped so the
// chapter never overflows the viewport and grows with the screen. In rem,
// because that chrome is: it shrinks with the fluid root size (index.css).
const CHROME_REM = 22.25;

// Scale statements from the content skill (kept until Rahul answers).
// "Competitions held" is the series number of the last race held, no "+"
// (content skill: "30 competitions held" until IROS 2026, the 31st, has
// run; /about and /race say 30 too). It follows events_map.json, where
// loadEventsMap marks a race held once its end date has passed, so the
// counter reads 31 after IROS without an edit; 30 until the file arrives.
const HELD_FALLBACK = 30;
const statsFor = (held: number) =>
  [
    { value: 90, suffix: "+", label: "universities" },
    { value: 20, suffix: "+", label: "countries" },
    { value: 1000, suffix: "+", label: "publications" },
    { value: held, suffix: undefined, label: "competitions held" },
  ] as const;
const STAT_COUNT = statsFor(HELD_FALLBACK).length;

// Reveal schedule in chapter progress (0..1 over the 260vh wrapper), landing
// v5 (docs/design/map-ticker-spec.svg, values copied literally): the pins pop
// in source array order (chronological, upcoming last), pin i of N at
// 0.06 + (0.82 - 0.06 - 0.03) * i / (N - 1); a country tints as its first pin
// pops; partner-only countries spread evenly over 0.40-0.79, so nothing moves
// after 0.82, the frame the last pin (IROS 2026) finishes popping. The four
// counters start at 0.06 + 0.015 j and all end at 0.82 with the pins.
const HEIGHT_VH = 260;
const ORIGIN_ID = "icra2022"; // ICRA 2022, Philadelphia: the one filled marker
const PINS = [0.06, 0.82] as const;
const POP = 0.03;
const PARTNER_SPAN = [0.4, 0.79] as const;
const STATS_START = 0.06;
const STATS_STAGGER = 0.015;
const STATS_END = PINS[1];
// Ticker swap (spec): the outgoing block fades in 120 ms; the incoming one
// fades in and rises 6 px in 220 ms, ease-out-expo.
/** Wheel geometry (v5 round two): rows at +-1 and +-2 around the current
 * one, shrinking and fading with distance; everything further is hidden. */
const WHEEL_STEP = 104;
const WHEEL_HEIGHT = 440;
const WHEEL_ROLL = 0.45;
const WHEEL_SCALE = [1, 0.72, 0.5] as const;
// Distance is told by size and colour (text-strong / text-body / text-muted,
// all AA on paper), not by opacity: faded text failed axe color-contrast.
const WHEEL_OPACITY = [1, 1, 1] as const;
function wheelSlot(d: number): { y: number; scale: number; opacity: number } {
  const k = Math.abs(d);
  if (k > 2) return { y: Math.sign(d) * WHEEL_STEP * 2.2, scale: WHEEL_SCALE[2], opacity: 0 };
  // Slots compress outward so the small rows sit close to the centre one
  // (row height ~110 px at 1440: +-1 at 104 px, +-2 at 172 px clear).
  const y = Math.sign(d) * (k === 1 ? WHEEL_STEP : WHEEL_STEP * 1.65);
  return { y, scale: WHEEL_SCALE[k], opacity: WHEEL_OPACITY[k] };
}

// Geometry in viewBox units (1600 wide land). At 1440x900 the map renders
// about 1,070 px wide next to the ticker column, so 6 units is a 4 px dot
// radius; under md the map is a quarter of that and every mark doubles.
const R = { pin: 5.5, ring: 11, glow: 30 } as const;
const FONT = { label: 13 } as const;
const LABEL_GAP = 6;
// Labels the director checks at 1440 (Philadelphia, Anchorage, Abu Dhabi, Rio,
// Jeju, Vienna, Pittsburgh) get first pick of the free space. Philadelphia
// (ICRA 2022, the home of the platform) leads: Cedric, 2026-08-22, "Boston
// should be replaced by Philadelphia", so Boston keeps its pin and glow but
// gives its label up.
const LABEL_PRIORITY = ["icra2022", "iv2023", "iros2024", "cdc2025", "iv2024", "icra2026", "iros2026"];
const LABEL_SKIP_CITIES = new Set(["Boston"]);

// Cedric's exact map spec (2026-08-22, replaces contract section 6 colours):
// four flat region tints by races held, no violet anywhere, one ink for
// region strokes, pin rings and labels.
const REGION_FILL = { four: "#71e4ea", two: "#a1ecf0", one: "#c4f2f5", partner: "#e4f7fa" } as const;
const MAP_INK = "#0b6b73";

type Anchor = "start" | "middle" | "end";
type Placed = { x: number; y: number; anchor: Anchor; text: string };
type Box = { x1: number; y1: number; x2: number; y2: number };

function overlaps(a: Box, b: Box): boolean {
  return a.x1 < b.x2 && a.x2 > b.x1 && a.y1 < b.y2 && a.y2 > b.y1;
}

function textBox(x: number, y: number, anchor: Anchor, text: string, fs: number): Box {
  const w = text.length * fs * 0.62;
  const x1 = anchor === "start" ? x : anchor === "end" ? x - w : x - w / 2;
  return { x1, y1: y - fs / 2, x2: x1 + w, y2: y + fs / 2 };
}

/**
 * Greedy label placement in viewBox units: one label per city, tried right /
 * left / above / below the pin, dropped when it would cross a pin or a placed
 * label. A labelDx/labelDy from the source file is a forced position.
 */
function placeLabels(pins: MapEvent[], r: number, fs: number): Map<string, Placed> {
  const placed = new Map<string, Placed>();
  const taken: Box[] = pins.map((p) => ({ x1: p.x - r, y1: p.y - r, x2: p.x + r, y2: p.y + r }));
  // Verified cities first (sanity set, then the upcoming races, then in
  // order); unverified pins come last so they can only add a "tbc" tag to a
  // city a verified race already labelled.
  const rank = (e: MapEvent) => {
    const i = LABEL_PRIORITY.indexOf(e.id);
    if (i >= 0) return i;
    if (!e.verified) return 1000 + pins.indexOf(e);
    if (e.status === "upcoming") return 100;
    return 200 + pins.indexOf(e);
  };
  const labelledCities = new Set<string>();
  const candidates = [...pins].sort((a, b) => rank(a) - rank(b));
  for (const e of candidates) {
    if (LABEL_SKIP_CITIES.has(e.city) || labelledCities.has(e.city)) continue;
    // One plain city name per city (no "tbc" text: the dashed ring says it).
    const text = e.city;
    const forcedAnchor: Anchor = e.labelDx === 0 ? "middle" : (e.labelDx ?? 1) < 0 ? "end" : "start";
    const tries: Array<[number, number, Anchor]> =
      e.labelDx !== undefined || e.labelDy !== undefined
        ? [[e.x + (e.labelDx ?? r + LABEL_GAP), e.y + (e.labelDy ?? 0), forcedAnchor]]
        : [
            [e.x + r + LABEL_GAP, e.y, "start"],
            [e.x - r - LABEL_GAP, e.y, "end"],
            [e.x, e.y - r - fs * 0.7, "middle"],
            [e.x, e.y + r + fs * 0.7, "middle"],
          ];
    const forced = tries.length === 1;
    for (const [x, y, anchor] of tries) {
      const box = textBox(x, y, anchor, text, fs);
      const inside = box.x1 >= 0 && box.x2 <= VB_W;
      if (forced || (inside && !taken.some((t) => overlaps(t, box)))) {
        taken.push(box);
        placed.set(e.id, { x, y, anchor, text });
        labelledCities.add(e.city);
        break;
      }
    }
  }
  return placed;
}

function regionFill(r: MapRegion): string {
  // A country with only an upcoming race is treated as a one-race host.
  const held = Math.max(r.held, r.upcoming > 0 ? 1 : 0);
  if (held >= 4) return REGION_FILL.four;
  if (held >= 2) return REGION_FILL.two;
  if (held >= 1) return REGION_FILL.one;
  return REGION_FILL.partner;
}

/** Screen-reader venue list: label, city, and the status when not held. */
function flashText(e: MapEvent): string {
  const tags = [e.label, e.city];
  if (e.status === "upcoming") tags.push("upcoming");
  else if (e.status === "virtual") tags.push("virtual");
  return tags.join(" · ");
}

function ordinalSuffix(n: number): string {
  const mod100 = n % 100;
  if (mod100 >= 11 && mod100 <= 13) return "th";
  const mod10 = n % 10;
  return mod10 === 1 ? "st" : mod10 === 2 ? "nd" : mod10 === 3 ? "rd" : "th";
}

/** The numbered series (spec): race pins with an official "Nth". Only these
 * enter the ticker; unnumbered race pins still pop on the map. */
const isNumbered = (e: MapEvent) => e.kind === "race" && typeof e.number === "number";

/** Ticker place line: "City, Country", a city-state once (Hong Kong). */
const placeText = (e: MapEvent) => (e.city === e.country ? e.city : `${e.city}, ${e.country}`);

/** Ticker status line, only when the race was not held in person. */
const statusText = (e: MapEvent) => (e.status === "upcoming" || e.status === "virtual" ? e.status : "");

/** Header flash line (below xl): the ticker's parts joined by " · ",
 * e.g. "31st · IROS 2026 · Pittsburgh · upcoming". */
function tickerLine(e: MapEvent): string {
  const parts = [`${e.number}${ordinalSuffix(e.number ?? 0)}`, e.label, e.city];
  const status = statusText(e);
  if (status) parts.push(status);
  return parts.join(" · ");
}

type WorldMapChapterProps = {
  className?: string;
};

// Event countries -> Natural Earth region names (mirrors build-world-map.mjs;
// Hong Kong's events count toward China's region, the pin stays on Hong Kong).
const NE_NAME: Record<string, string> = {
  "United States": "United States of America",
  "Republic of Korea": "South Korea",
  "Hong Kong": "China",
};
const regionNameFor = (country: string) => NE_NAME[country] ?? country;

type Timing = { pinAt: Map<string, number>; regionAt: Map<string, number> };

/** The chronological schedule: pin i of N pops at an even step through the
 * pin window in source array order, a region tints at its first pin, and the
 * partner-only regions spread evenly over PARTNER_SPAN. */
function arrayTiming(pins: MapEvent[], regions: MapRegion[]): Timing {
  const span = PINS[1] - PINS[0] - POP;
  const n = pins.length;
  const pinAt = new Map<string, number>();
  pins.forEach((e, i) => pinAt.set(e.id, n > 1 ? PINS[0] + (span * i) / (n - 1) : PINS[0]));
  const regionAt = new Map<string, number>();
  const partnerOnly: string[] = [];
  for (const r of regions) {
    const times = pins.filter((e) => regionNameFor(e.country) === r.name).map((e) => pinAt.get(e.id) ?? PINS[1]);
    if (times.length) regionAt.set(r.name, Math.min(...times));
    else partnerOnly.push(r.name);
  }
  const m = partnerOnly.length;
  const partnerStep = m > 1 ? (PARTNER_SPAN[1] - PARTNER_SPAN[0]) / (m - 1) : 0;
  partnerOnly.forEach((name, k) => regionAt.set(name, PARTNER_SPAN[0] + k * partnerStep));
  return { pinAt, regionAt };
}

/**
 * Landing section 03 / Community (serves the sponsor and the press, audiences
 * skill): a pinned paper chapter. The base state is the bare land as hairline
 * slate outlines; as the reader scrolls, the venues pop in chronological
 * order from ESWeek 2016 to IROS 2026, a country tints cyan (deeper with more
 * races held) as its first venue lands, partner-only countries tint palest
 * through the middle of the run, and the four scale numbers count up to land
 * with the last pin. At xl a 280 px ticker column right of the map names the
 * competition that just popped ("27th / ICRA 2026 / Vienna, Austria"); below
 * xl the header's flash line carries the same text. Philadelphia is the one
 * filled marker; no violet anywhere. Header above the map, counters and
 * legend below; the map takes the width the viewport height allows (up to
 * 1,800 px). Reduced motion and no-JS get the final state: every region, pin
 * and number, and the ticker on IROS 2026. Below `desktop:` (phones in either
 * orientation, mobile pass L-3) nothing pins either: the same final state as
 * an ordinary section, the map across the full column, the four counters
 * counting up once as they come into view.
 */
export default function WorldMapChapter({ className = "" }: WorldMapChapterProps) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const flashRef = useRef<HTMLParagraphElement>(null);
  const wheelRef = useRef<HTMLDivElement>(null);
  const statRefs = useRef<RefObject<StatTickerHandle | null>[]>(Array.from({ length: STAT_COUNT }, () => createRef<StatTickerHandle>()));
  const glowId = useId();
  const reduced = usePrefersReducedMotion();
  const desktop = useDesktop();
  const [data, setData] = useState<EventsMap | null>(null);

  useEffect(() => {
    let live = true;
    loadEventsMap()
      .then((d) => {
        if (live) setData(d);
      })
      .catch(() => {
        if (live) setData(null);
      });
    return () => {
      live = false;
    };
  }, []);

  // Mobile renders the map at a quarter of the desktop width: double the marks.
  const k = desktop ? 1 : 2;
  const rPin = R.pin * k;
  const rRing = R.ring * k;
  const rGlow = R.glow * k;

  const pins = useMemo(
    () => (data?.events ?? []).filter((e) => !(e.lat === 0 && e.lng === 0)),
    [data],
  );
  const regions = useMemo(() => data?.regions ?? [], [data]);
  const origin = useMemo(() => pins.find((e) => e.id === ORIGIN_ID), [pins]);
  const series = useMemo(() => pins.filter(isNumbered), [pins]);
  const stats = useMemo(() => {
    const held = (data?.events ?? [])
      .filter((e) => isNumbered(e) && e.status !== "upcoming")
      .reduce((max, e) => Math.max(max, e.number ?? 0), 0);
    return statsFor(held || HELD_FALLBACK);
  }, [data]);
  const last: MapEvent | undefined = series[series.length - 1];
  const timing = useMemo(() => arrayTiming(pins, regions), [pins, regions]);
  const labels = useMemo(() => placeLabels(pins, rPin, FONT.label), [pins, rPin]);
  const finalLine = last ? tickerLine(last) : "";

  useGSAP(
    () => {
      const wrap = wrapRef.current;
      if (!wrap || reduced || !desktop || pins.length === 0) return;
      const mm = gsap.matchMedia();
      mm.add(`${MOTION_OK_QUERY} and ${DESKTOP_QUERY}`, () => {
        const regionEls = gsap.utils.toArray<SVGPathElement>("[data-region]", wrap);
        const glowEls = gsap.utils.toArray<SVGCircleElement>("[data-glow]", wrap);
        const pinEls = gsap.utils.toArray<SVGGElement>("[data-pin]", wrap);
        const flashEl = flashRef.current;
        const glowById = new Map(glowEls.map((el) => [el.dataset.glow, el]));
        const seriesAt = series.map((e) => timing.pinAt.get(e.id) ?? PINS[0]);

        // Ticker wheel (Cedric, v5 round two: "like a scroll wheel in a
        // timer"): every numbered race is a row; the current one sits at the
        // centre full size, the two before and after it shrink and fade with
        // distance, the rest are hidden. A swap rolls every row to its new
        // slot. The first call (progress 0) just clears the markup's final
        // state.
        const rows = wheelRef.current
          ? gsap.utils.toArray<HTMLElement>("[data-wheel-row]", wheelRef.current)
          : [];
        // GSAP owns the transform from here: yPercent -50 replaces the
        // markup's translateY(-50%) and y/scale ride on top of it.
        rows.forEach((row) => gsap.set(row, { yPercent: -50, clearProps: "visibility" }));
        // Deliberately NOT contextSafe. These two run on every scrub tick,
        // and a contextSafe call re-enters gsap's Context.add wrapper, which
        // does `prev.data.push(self)` on every invocation with no dedup. Under
        // StrictMode's double mount that made two of this chapter's contexts
        // land in each other's `data`; Context.getTweens then recursed until
        // the stack blew, and because the throw happened during the landing's
        // unmount it took the whole React root with it — every client-side
        // navigation painted a white page until a manual reload. The tweens
        // these two create are killed in this block's cleanup instead.
        const swap = ((i: number, animate: boolean) => {
          rows.forEach((row, j) => {
            const t = wheelSlot(j - i);
            row.dataset.d = String(Math.min(2, Math.abs(j - i)));
            gsap.to(row, {
              y: t.y,
              scale: t.scale,
              autoAlpha: t.opacity,
              duration: animate ? WHEEL_ROLL : 0,
              ease: EASE_OUT_EXPO,
              overwrite: true,
            });
          });
        });

        let lastIndex = -2;
        const flash = (() => {
          if (flashEl) gsap.fromTo(flashEl, { opacity: 0.25 }, { opacity: 1, duration: 0.35, overwrite: true });
        });

        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: wrap,
            start: "top top",
            end: "bottom bottom",
            scrub: 0.6,
          },
          onUpdate: () => update(tl.progress()),
        });
        const update = (p: number) => {
          // Ticker: the latest numbered race whose pop is past its midpoint.
          let i = -1;
          for (let j = 0; j < seriesAt.length; j += 1) {
            if (p >= seriesAt[j] + POP / 2) i = j;
            else break;
          }
          if (i !== lastIndex) {
            const first = lastIndex === -2;
            lastIndex = i;
            const e = i >= 0 ? series[i] : undefined;
            if (flashEl) {
              // Non-breaking space keeps the line's height: no jump.
              flashEl.textContent = e ? tickerLine(e) : " ";
              if (e && !first) flash();
            }
            swap(i, !first);
          }
          // Every counter lands at STATS_END, the frame the last pin finishes.
          statRefs.current.forEach((ref, j) => {
            const start = STATS_START + j * STATS_STAGGER;
            ref.current?.setProgress((p - start) / (STATS_END - start));
          });
        };
        // The markup carries the final state (reduced motion / no JS); the
        // pinned run starts from the bare land the moment the timeline exists.
        update(0);

        // A full-length proxy tween pins the timeline's duration to 1, so its
        // progress is chapter progress whatever the last tween's end.
        tl.to({ t: 0 }, { t: 1, duration: 1, ease: "none" }, 0);

        // Countries tint as the run reaches their first venue.
        regionEls.forEach((el) => {
          const t = timing.regionAt.get(el.dataset.region ?? "") ?? PINS[1];
          tl.fromTo(el, { opacity: 0 }, { opacity: 1, duration: POP * 2, ease: "none" }, Math.max(0, t - POP));
        });

        // Pins pop in chronological order; each race held brings its glow,
        // labels follow in the second half of the pop so every pin is done at
        // t + POP.
        pinEls.forEach((g) => {
          const t = timing.pinAt.get(g.dataset.pin ?? "") ?? PINS[0];
          const dot = g.querySelector<SVGCircleElement>("[data-dot]");
          const ring = g.querySelector<SVGCircleElement>("[data-ring]");
          const label = g.querySelector<SVGTextElement>("[data-label]");
          const glow = glowById.get(g.dataset.pin);
          if (ring) {
            const r = Number(ring.getAttribute("r"));
            tl.fromTo(ring, { attr: { r: 0 } }, { attr: { r }, duration: POP, ease: "power2.out" }, t);
          }
          if (glow) {
            const r = Number(glow.getAttribute("r"));
            tl.fromTo(glow, { attr: { r: 0 } }, { attr: { r }, duration: POP, ease: "power2.out" }, t);
          }
          if (dot) {
            const r = Number(dot.getAttribute("r"));
            tl.fromTo(dot, { attr: { r: 0 } }, { attr: { r }, duration: POP, ease: "back.out(1.6)" }, t);
          }
          if (label) tl.fromTo(label, { opacity: 0 }, { opacity: 1, duration: POP / 2, ease: "none" }, t + POP / 2);
        });
        wrap.dataset.mapReady = "1";

        // swap/flash tweens are created outside any context (see above), so
        // the context revert would not reach them. Kill them here.
        return () => {
          gsap.killTweensOf(rows);
          if (flashEl) gsap.killTweensOf(flashEl);
        };
      });
      document.fonts?.ready?.then(() => ScrollTrigger.refresh());
    },
    { scope: wrapRef, dependencies: [pins, regions, reduced, desktop, k, timing, series], revertOnUpdate: true },
  );

  // The map's width cap follows the viewport height.
  const chapterVars = {
    // Floor: on a short viewport (landscape phone) the height-driven cap
    // would leave a sliver, so the width takes over below 420px.
    "--map-max": `max(26.25rem, calc((100svh - ${CHROME_REM}rem) * ${ASPECT.toFixed(4)}))`,
    // Landscape phone (compact, sm and up): the width at which the whole map
    // fits the window under the bar, so it can be seen in one piece.
    "--map-fit": `calc((100svh - var(--spacing-nav) - 1.5rem) * ${ASPECT.toFixed(4)})`,
  } as CSSProperties;

  const svg = (
    <svg
      data-map-svg
      viewBox={VIEWBOX}
      className="block h-auto w-full"
      role="img"
      aria-labelledby="community-map-title"
      aria-describedby="community-map-desc"
    >
      <title id="community-map-title">World map of RoboRacer competition venues and partner countries since 2016</title>
      <desc id="community-map-desc">
        Countries that hosted a competition are tinted cyan, deeper with more races; countries with partner
        institutions and no race yet carry the palest tint. Rings mark every competition venue, with a glow under
        each race held; a dashed ring means the race is still to come or the venue is still to be confirmed. The
        one filled dot is Philadelphia, where the platform started.
      </desc>
      <defs>
        <radialGradient id={glowId}>
          <stop offset="0" className="[stop-color:var(--color-rr-cyan)]" stopOpacity={0.26} />
          <stop offset="1" className="[stop-color:var(--color-rr-cyan)]" stopOpacity={0} />
        </radialGradient>
      </defs>
      <path
        d={LAND_PATH}
        fill="none"
        stroke={LAND_STROKE}
        strokeOpacity={0.32}
        strokeWidth={0.9}
        strokeLinejoin="round"
        vectorEffect="non-scaling-stroke"
      />
      <g aria-hidden="true">
        {regions.map((r) => (
          <path
            key={r.name}
            data-region={r.name}
            d={r.d}
            fill={regionFill(r)}
            stroke={MAP_INK}
            strokeOpacity={0.35}
            strokeWidth={0.7}
            strokeLinejoin="round"
            vectorEffect="non-scaling-stroke"
          />
        ))}
      </g>
      <g aria-hidden="true">
        {pins.map((e) =>
          e.kind === "race" && e.status === "held" ? (
            <circle key={e.id} data-glow={e.id} cx={e.x} cy={e.y} r={rGlow} fill={`url(#${glowId})`} />
          ) : null,
        )}
      </g>
      <g aria-hidden="true">
        {pins.map((e) => {
          // Philadelphia is the one filled marker; a second venue in the same
          // city adds nothing on top of it.
          const originCity = origin !== undefined && e.city === origin.city;
          if (originCity && e.id !== ORIGIN_ID) return null;
          const dashed = !originCity && (!e.verified || e.status !== "held");
          const label = labels.get(e.id);
          return (
            <g key={e.id} data-pin={e.id} transform={`translate(${e.x} ${e.y})`}>
              {originCity ? (
                <>
                  <circle
                    data-ring
                    r={rRing}
                    fill="var(--color-paper-50)"
                    fillOpacity={0.7}
                    stroke={MAP_INK}
                    strokeOpacity={0.6}
                    strokeWidth={1.7}
                    vectorEffect="non-scaling-stroke"
                  />
                  <circle data-dot r={rPin} fill={MAP_INK} />
                </>
              ) : (
                <circle
                  data-dot
                  r={rPin}
                  fill="var(--color-paper-50)"
                  stroke={MAP_INK}
                  strokeOpacity={dashed ? 0.45 : 1}
                  strokeWidth={1.7}
                  strokeDasharray={dashed ? "2.5 2" : undefined}
                  vectorEffect="non-scaling-stroke"
                />
              )}
              {label && (
                <text
                  data-label
                  x={label.x - e.x}
                  y={label.y - e.y}
                  textAnchor={label.anchor}
                  dominantBaseline="middle"
                  fontSize={FONT.label}
                  fill={MAP_INK}
                  fillOpacity={0.9}
                  className="hidden font-mono desktop:block"
                >
                  {label.text}
                </text>
              )}
            </g>
          );
        })}
      </g>
    </svg>
  );

  const header = (
    <div className="grid gap-3 md:grid-cols-12 md:items-end md:gap-6">
      <div className="md:col-span-6">
        <p className="mb-3 flex items-center gap-2 font-mono text-small text-text-muted">
          <span aria-hidden="true" className="h-1 w-1 bg-ink-950" />
          <span>03</span>
        </p>
        <h2 id="community-title" className="font-display text-display-m font-semibold text-text-strong">
          Community
        </h2>
        <p className="mt-3 max-w-[40ch] font-display text-lead font-semibold text-text-strong">Teams from around the world</p>
      </div>
      <div className="md:col-span-5 md:col-start-8">
        <p className="max-w-[38ch] text-lead text-text-body">
          Teams around the world build and race RoboRacer cars.
        </p>
        {/* Below xl the ticker lives here as one mono line; at xl the column
            right of the map takes over. */}
        <p
          ref={flashRef}
          className="mt-2 min-h-[1.5em] font-mono text-small text-text-muted xl:hidden"
          aria-live="off"
          data-map-flash
        >
          {finalLine}
        </p>
      </div>
    </div>
  );

  // Competition ticker (xl only): hairline rule, "competition" eyebrow, then
  // the wheel: one row per numbered race (ordinal, conference, place, status),
  // the current one centred and full size, neighbours smaller and fainter
  // (wheelSlot). The markup carries the final state (last entry centred) for
  // reduced motion / no JS; the sr-only venue list below the map is the
  // accessible version.
  const lastIndex = series.length - 1;
  const ticker = (
    <div aria-hidden="true" className="hidden xl:block" data-ticker>
      <div className="border-t border-text-strong/10 pt-4">
        <p className="font-mono text-small text-text-muted">competition</p>
        <div ref={wheelRef} className="relative mt-2" style={{ height: WHEEL_HEIGHT }} data-wheel>
          {series.map((e, j) => {
            const t = wheelSlot(j - lastIndex);
            return (
              <div
                key={e.id}
                data-wheel-row={j}
                data-d={Math.min(2, Math.abs(j - lastIndex))}
                className="absolute inset-x-0 top-1/2 origin-left text-text-strong transition-colors duration-[var(--duration-base)] data-[d=1]:text-text-body data-[d=2]:text-text-muted"
                style={{
                  transform: `translateY(calc(-50% + ${t.y}px)) scale(${t.scale})`,
                  opacity: t.opacity,
                  visibility: t.opacity === 0 ? "hidden" : "visible",
                }}
              >
                <p className="font-display text-display-l font-semibold leading-none">
                  <span>{e.number}</span>
                  <span className="relative -top-[0.82em] inline-block text-[0.5em] leading-none">{ordinalSuffix(e.number ?? 0)}</span>
                </p>
                <p className="mt-1 font-display text-[1.125rem] leading-tight font-semibold">{e.label}</p>
                <p className="mt-0.5 font-mono text-small">
                  {placeText(e)}
                  {statusText(e) && <span className="text-text-muted"> · {statusText(e)}</span>}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );

  // Desktop: the pinned run drives the counters (progress). Compact: each
  // counts up once when it is fully in view (time), 0.15 s apart; the key
  // remounts a tile if the layout switches.
  const counterMode = desktop ? "progress" : "time";
  const counters = (
    <div className="grid grid-cols-2 gap-x-8 gap-y-6 sm:flex sm:items-end sm:gap-x-10">
      {stats.map((s, j) => (
        <StatTicker
          key={`${s.label}-${counterMode}`}
          ref={statRefs.current[j]}
          value={s.value}
          suffix={s.suffix}
          label={s.label}
          on="paper"
          mode={counterMode}
          delay={desktop ? 0 : j * 0.15}
        />
      ))}
    </div>
  );

  const legend = (
    <ul aria-label="Map key" className="flex flex-wrap items-center gap-x-6 gap-y-2 font-mono text-small text-text-muted">
      <li className="flex items-center gap-2">
        <span
          aria-hidden="true"
          className="inline-block h-2.5 w-2.5"
          style={{ background: REGION_FILL.four, border: `1px solid ${MAP_INK}59` }}
        />
        hosted a race, deeper with more
      </li>
      <li className="flex items-center gap-2">
        <span
          aria-hidden="true"
          className="inline-block h-2.5 w-2.5"
          style={{ background: REGION_FILL.partner, border: `1px solid ${MAP_INK}59` }}
        />
        partner institutions
      </li>
    </ul>
  );

  const venues = (
    <ul className="sr-only">
      {pins.map((e) => (
        <li key={e.id}>{flashText(e)}</li>
      ))}
    </ul>
  );

  // Toward the edges (Cedric): the map runs on a 1,800 px bleed with 24 px
  // margins, capped by the viewport height so the pinned chapter always fits.
  // At xl the row is a two-column grid (spec): the map cell takes
  // min(--map-max, 100%), the ticker column 280 px, 40 px between, centred.
  // Below `desktop:` nothing pins: on a portrait phone the map bleeds to the
  // full screen width; on a landscape one it takes the width at which it
  // fits the window under the bar (--map-fit).
  const layout = (
    <div className="mx-auto w-full max-w-page px-6">
      {header}
      <div className="mt-4 md:mt-5 xl:grid xl:grid-cols-[minmax(0,1fr)_17.5rem] xl:items-center xl:gap-10">
        <div className="mx-auto w-full max-sm:-mx-6 max-sm:w-auto compact:sm:max-w-[min(var(--map-fit),100%)] desktop:max-w-[min(var(--map-max),100%)]">
          {svg}
        </div>
        {ticker}
      </div>
      {venues}
      <div className="mt-4 flex flex-col gap-5 border-t border-ink-950/10 pt-4 md:mt-5 md:flex-row md:items-end md:justify-between">
        {counters}
        {legend}
      </div>
    </div>
  );

  if (reduced || !desktop) {
    return (
      <section
        aria-labelledby="community-title"
        className={`bg-paper-50 py-section text-text-body ${className}`}
        style={chapterVars}
      >
        {layout}
      </section>
    );
  }

  return (
    <section aria-labelledby="community-title" className={`bg-paper-50 text-text-body ${className}`} style={chapterVars}>
      <div ref={wrapRef} data-map-chapter style={{ height: `${HEIGHT_VH}vh` }}>
        {/* Centered in the viewport below the fixed nav (--spacing-nav). */}
        <div className="sticky top-0 flex min-h-svh flex-col justify-center pb-6 pt-[calc(var(--spacing-nav)+1rem)]">
          {layout}
        </div>
      </div>
    </section>
  );
}
