import { createRef, useEffect, useId, useMemo, useRef, useState, useSyncExternalStore, type RefObject } from "react";
import { loadEventsMap, type EventsMap, type MapEvent, type MapRegion } from "../../lib/data";
import { gsap, useGSAP, MOTION_OK_QUERY, ScrollTrigger } from "../../lib/motion";
import { usePrefersReducedMotion } from "../../hooks/usePrefersReducedMotion";
import StatCounter, { type StatCounterHandle } from "./StatCounter";
// Generated by scripts/build-world-map.mjs (Natural Earth I, 1600 wide, height
// fitted to the land). Inlined so the land path, the regions and the pins share
// one coordinate space.
import worldLandSvg from "../../../public/media/map/world-land.svg?raw";

const LAND_PATH = /\sd="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "";
const VIEWBOX = /viewBox="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "0 0 1600 706";
const [, , VB_W, VB_H] = VIEWBOX.split(" ").map(Number);

// Overlay frame (xl and up, landing-v4 section 6): the land keeps its
// coordinates; the viewBox grows left and down so the header sits over open
// North Pacific, the counters over the South Pacific and the legend below
// Australia. 450 units left of the antimeridian clear Alaska's tip (x 210) and
// Hawaii (x 110, y 300) for a header 27.5 percent of the map wide; 60 units
// below Patagonia and New Zealand give the legend a free row.
const PAD_LEFT = 450;
const PAD_BOTTOM = 60;
const VIEWBOX_OVERLAY = `${-PAD_LEFT} 0 ${VB_W + PAD_LEFT} ${VB_H + PAD_BOTTOM}`;

/**
 * `regions` from events_map.json (one Natural Earth path per country that
 * hosted a competition or fields a partner). Typed here until
 * src/lib/data.ts carries it (stream D owns that file in v4).
 */

// Scale statements from the content skill (kept until Rahul answers).
const STATS = [
  { value: 90, suffix: "+", label: "universities" },
  { value: 20, suffix: "+", label: "countries" },
  { value: 1000, suffix: "+", label: "publications" },
  { value: 30, suffix: "", label: "competitions held" },
] as const;

// Pin schedule in chapter progress (0..1 over the 260vh wrapper), landing-v3
// section 6, kept in v4: regions take the old country step.
const HEIGHT_VH = 260;
const REGIONS_IN = [0.05, 0.4] as const;
const PINS = [0.35, 0.85] as const;
const POP = 0.03;
// Counters start together with the first pins and finish before the hold; a
// visible stagger left the last tile reading "0+" mid-pin (critique).
const STATS_START = 0.36;
const STATS_STAGGER = 0.015;
const STATS_DURATION = 0.45;

// Geometry in viewBox units (1600 wide land). The overlay frame renders the
// land at about 1,076 px at 1440, so 6 units is a 4 px dot radius; under md the
// map is a quarter of that and every mark doubles.
const R = { pin: 6, next: 8, glow: 48, pulseFrom: 8, pulseTo: 38 } as const;
const FONT = { label: 22 } as const;
const LABEL_GAP = 6;
// Labels the director checks at 1440 (Philadelphia, Anchorage, Abu Dhabi, Rio,
// Jeju, Vienna, Pittsburgh) get first pick of the free space. Philadelphia
// (ICRA 2022, the home of the platform) leads: Cedric, 2026-08-22, "Boston
// should be replaced by Philadelphia", so Boston keeps its pin and glow but
// gives its label up.
const LABEL_PRIORITY = ["icra2022", "iv2023", "iros2024", "cdc2025", "iv2024", "icra2026", "iros2026"];
const LABEL_SKIP_CITIES = new Set(["Boston"]);

// Region fills by held count (section 6 table); never above 0.60 so the pins
// stay the brightest thing on the map. Partner-only countries are violet.
const REGION_TIERS = [
  { min: 4, fill: 0.6, stroke: 0.85 },
  { min: 2, fill: 0.4, stroke: 0.65 },
  { min: 1, fill: 0.22, stroke: 0.47 },
] as const;
const PARTNER_TIER = { fill: 0.22, stroke: 0.47 } as const;

const DESKTOP_QUERY = "(min-width: 768px)";
const OVERLAY_QUERY = "(min-width: 1280px)";

type Anchor = "start" | "middle" | "end";
type Placed = { x: number; y: number; anchor: Anchor; text: string };
type Box = { x1: number; y1: number; x2: number; y2: number };

function useMatchMedia(query: string): boolean {
  return useSyncExternalStore(
    (onChange) => {
      const mql = window.matchMedia(query);
      mql.addEventListener("change", onChange);
      return () => mql.removeEventListener("change", onChange);
    },
    () => window.matchMedia(query).matches,
    () => true,
  );
}

function overlaps(a: Box, b: Box): boolean {
  return a.x1 < b.x2 && a.x2 > b.x1 && a.y1 < b.y2 && a.y2 > b.y1;
}

function textBox(x: number, y: number, anchor: Anchor, text: string, fs: number): Box {
  const w = text.length * fs * 0.62;
  const x1 = anchor === "start" ? x : anchor === "end" ? x - w : x - w / 2;
  return { x1, y1: y - fs / 2, x2: x1 + w, y2: y + fs / 2 };
}

/**
 * Greedy label placement in viewBox units: one label per city, tried right /
 * left / above / below the pin, dropped when it would cross a pin or a placed
 * label. A labelDx/labelDy from the source file is a forced position.
 */
function placeLabels(pins: MapEvent[], r: number, fs: number): Map<string, Placed> {
  const placed = new Map<string, Placed>();
  const taken: Box[] = pins.map((p) => ({ x1: p.x - r, y1: p.y - r, x2: p.x + r, y2: p.y + r }));
  // Verified cities first (sanity set, then the upcoming races, then in
  // order); unverified pins come last so they can only add a "tbc" tag to a
  // city a verified race already labelled.
  const rank = (e: MapEvent) => {
    const i = LABEL_PRIORITY.indexOf(e.id);
    if (i >= 0) return i;
    if (!e.verified) return 1000 + pins.indexOf(e);
    if (e.status === "upcoming") return 100;
    return 200 + pins.indexOf(e);
  };
  const labelledCities = new Set<string>();
  const candidates = [...pins].sort((a, b) => rank(a) - rank(b));
  for (const e of candidates) {
    if (LABEL_SKIP_CITIES.has(e.city)) continue;
    const cityDone = labelledCities.has(e.city);
    if (cityDone && e.verified) continue;
    const verifiedHere = pins.some((p) => p.verified && p.city === e.city);
    const text = e.verified ? e.city : cityDone || verifiedHere ? "tbc" : `${e.city} · tbc`;
    const forcedAnchor: Anchor = e.labelDx === 0 ? "middle" : (e.labelDx ?? 1) < 0 ? "end" : "start";
    const tries: Array<[number, number, Anchor]> =
      e.labelDx !== undefined || e.labelDy !== undefined
        ? [[e.x + (e.labelDx ?? r + LABEL_GAP), e.y + (e.labelDy ?? 0), forcedAnchor]]
        : [
            [e.x + r + LABEL_GAP, e.y, "start"],
            [e.x - r - LABEL_GAP, e.y, "end"],
            [e.x, e.y - r - fs * 0.7, "middle"],
            [e.x, e.y + r + fs * 0.7, "middle"],
          ];
    const forced = tries.length === 1;
    for (const [x, y, anchor] of tries) {
      const box = textBox(x, y, anchor, text, fs);
      const inside = box.x1 >= 0 && box.x2 <= VB_W;
      if (forced || (inside && !taken.some((t) => overlaps(t, box)))) {
        taken.push(box);
        placed.set(e.id, { x, y, anchor, text });
        labelledCities.add(e.city);
        break;
      }
    }
  }
  return placed;
}

function regionStyle(r: MapRegion) {
  // A country with only an upcoming race is treated as a one-race host (no
  // such country today: every upcoming venue already hosted).
  const held = Math.max(r.held, r.upcoming > 0 ? 1 : 0);
  const hosted = held > 0;
  const tier = hosted ? (REGION_TIERS.find((t) => held >= t.min) ?? REGION_TIERS[2]) : PARTNER_TIER;
  // An unverified partner country (no race on record, affiliation still to be
  // read from a source) keeps the outline but half the fill.
  return { hosted, fill: r.verified ? tier.fill : tier.fill / 2, stroke: tier.stroke };
}

function flashText(e: MapEvent): string {
  const tags = [e.label, e.city];
  if (e.status === "upcoming") tags.push("upcoming");
  else if (e.status === "virtual") tags.push("virtual");
  if (!e.verified) tags.push("tbc");
  return tags.join(" · ");
}

type WorldMapChapterProps = {
  className?: string;
};

/**
 * Landing section 05 / Community (serves the sponsor and the press, audiences
 * skill): a pinned ink chapter. Phase 1 tints the host and partner countries
 * (cyan by races held, violet for partner-only), phase 2 pops every
 * competition venue in chronological order with a glow under each race held
 * while the four scale numbers count up, phase 3 holds with IROS 2026 pulsing
 * as the only violet pin. From xl the header, the counters and the legend sit
 * over the ocean of a container-wide map; below xl they stack around it.
 * Reduced motion and no-JS get the final state: every region, pin and number.
 */
export default function WorldMapChapter({ className = "" }: WorldMapChapterProps) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const flashRef = useRef<HTMLParagraphElement>(null);
  const statRefs = useRef<RefObject<StatCounterHandle | null>[]>(STATS.map(() => createRef<StatCounterHandle>()));
  const glowId = useId();
  const reduced = usePrefersReducedMotion();
  const desktop = useMatchMedia(DESKTOP_QUERY);
  const overlay = useMatchMedia(OVERLAY_QUERY);
  const [data, setData] = useState<EventsMap | null>(null);

  useEffect(() => {
    let live = true;
    loadEventsMap()
      .then((d) => {
        if (live) setData(d);
      })
      .catch(() => {
        if (live) setData(null);
      });
    return () => {
      live = false;
    };
  }, []);

  // Mobile renders the map at a quarter of the desktop width: double the marks.
  const k = desktop ? 1 : 2;
  const rPin = R.pin * k;
  const rNext = R.next * k;
  const rGlow = R.glow * k;

  const pins = useMemo(
    () => (data?.events ?? []).filter((e) => !(e.lat === 0 && e.lng === 0)),
    [data],
  );
  // Already sorted by held count, biggest first (build-world-map.mjs).
  const regions = useMemo(() => data?.regions ?? [], [data]);
  const next = useMemo(() => [...pins].reverse().find((e) => e.status === "upcoming"), [pins]);
  const labels = useMemo(() => placeLabels(pins, rPin, FONT.label), [pins, rPin]);
  const finalFlash = next ? `coming up · ${next.city}` : "";

  useGSAP(
    (_context, contextSafe) => {
      const wrap = wrapRef.current;
      if (!wrap || reduced || pins.length === 0) return;
      const mm = gsap.matchMedia();
      mm.add(MOTION_OK_QUERY, () => {
        const regionEls = gsap.utils.toArray<SVGPathElement>("[data-region]", wrap);
        const glowEls = gsap.utils.toArray<SVGCircleElement>("[data-glow]", wrap);
        const pinEls = gsap.utils.toArray<SVGGElement>("[data-pin]", wrap);
        const pulseWrap = wrap.querySelector<SVGGElement>("[data-pulse-wrap]");
        const pulse = wrap.querySelector<SVGCircleElement>("[data-pulse]");
        const flashEl = flashRef.current;
        const glowById = new Map(glowEls.map((el) => [el.dataset.glow, el]));

        const pinStep = (PINS[1] - PINS[0] - POP) / Math.max(pinEls.length - 1, 1);
        let lastIndex = -2;
        const flash = contextSafe?.(() => {
          if (flashEl) gsap.fromTo(flashEl, { opacity: 0.25 }, { opacity: 1, duration: 0.35, overwrite: true });
        });

        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: wrap,
            start: "top top",
            end: "bottom bottom",
            scrub: 0.6,
            onToggle: (self) => pulseTween.paused(!self.isActive),
          },
          onUpdate: () => update(tl.progress()),
        });
        const update = (p: number) => {
          // Ticker: the latest pin whose pop is half way.
          const i = Math.min(Math.floor((p - PINS[0] - POP / 2) / pinStep), pinEls.length - 1);
          if (i !== lastIndex) {
            lastIndex = i;
            const e = pins[i];
            if (flashEl) {
              if (i < 0) {
                // Non-breaking space keeps the line's height: no jump.
                flashEl.textContent = " ";
              } else {
                flashEl.textContent = e === next ? finalFlash : flashText(e);
                flash?.();
              }
            }
          }
          statRefs.current.forEach((ref, j) => {
            ref.current?.setProgress((p - STATS_START - j * STATS_STAGGER) / STATS_DURATION);
          });
        };
        // The markup carries the final state (reduced motion / no JS); the
        // pinned run starts from phase 0 the moment the timeline exists.
        update(0);

        // Phase 1: regions fade in, biggest host first.
        if (regionEls.length) {
          const regionStagger = (REGIONS_IN[1] - REGIONS_IN[0] - 0.06) / Math.max(regionEls.length - 1, 1);
          tl.fromTo(regionEls, { opacity: 0 }, { opacity: 1, duration: 0.06, stagger: regionStagger, ease: "none" }, REGIONS_IN[0]);
        }

        // Phase 2: pins pop in array (chronological) order, each race held
        // brings its glow, labels follow.
        pinEls.forEach((g, i) => {
          const t = PINS[0] + i * pinStep;
          const dot = g.querySelector<SVGCircleElement>("[data-dot]");
          const label = g.querySelector<SVGTextElement>("[data-label]");
          const glow = glowById.get(g.dataset.pin);
          if (glow) {
            const r = Number(glow.getAttribute("r"));
            tl.fromTo(glow, { attr: { r: 0 } }, { attr: { r }, duration: POP * 2, ease: "power2.out" }, t);
          }
          if (dot) {
            const r = Number(dot.getAttribute("r"));
            tl.fromTo(dot, { attr: { r: 0 } }, { attr: { r }, duration: POP, ease: "back.out(1.6)" }, t);
          }
          if (label) tl.fromTo(label, { opacity: 0 }, { opacity: 1, duration: POP, ease: "none" }, t + POP / 2);
        });
        if (pulseWrap) {
          // Hidden from creation (a zero-duration set at position 0 does not
          // render at progress 0); revealed once the last pin has landed.
          gsap.set(pulseWrap, { autoAlpha: 0 });
          tl.set(pulseWrap, { autoAlpha: 1 }, PINS[1] + 0.005);
        }
        // Phase 3: hold. The next-race ring pulses on its own clock.
        const pulseTween = pulse
          ? gsap.fromTo(
              pulse,
              { attr: { r: R.pulseFrom * k }, opacity: 0.8 },
              { attr: { r: R.pulseTo * k }, opacity: 0, duration: 2.4, repeat: -1, ease: "power1.out", paused: true },
            )
          : gsap.to({}, { duration: 0 });

        wrap.dataset.mapReady = "1";
      });
      document.fonts?.ready?.then(() => ScrollTrigger.refresh());
    },
    { scope: wrapRef, dependencies: [pins, regions, reduced, k, overlay], revertOnUpdate: true },
  );

  const violet = "var(--color-rr-violet)";

  const svg = (
    <svg
      data-map-svg
      viewBox={overlay ? VIEWBOX_OVERLAY : VIEWBOX}
      className="block h-auto w-full max-h-[35svh] text-text-on-ink xl:max-h-none"
      role="img"
      aria-labelledby="community-map-title"
      aria-describedby="community-map-desc"
    >
      <title id="community-map-title">World map of RoboRacer competition venues and partner countries since 2016</title>
      <desc id="community-map-desc">
        Countries that hosted a competition are tinted cyan, deeper with more races; countries with partner
        institutions and no race yet are tinted violet. Dots mark every competition venue, with a glow under each
        race held, hollow when the race ran online, is still to come, or the venue is still to be confirmed. The
        violet dot is the next competition.
      </desc>
      <defs>
        <radialGradient id={glowId}>
          <stop offset="0" className="[stop-color:var(--color-rr-cyan)]" stopOpacity={0.35} />
          <stop offset="1" className="[stop-color:var(--color-rr-cyan)]" stopOpacity={0} />
        </radialGradient>
      </defs>
      <path
        d={LAND_PATH}
        fill="currentColor"
        fillOpacity={0.1}
        stroke="currentColor"
        strokeOpacity={0.18}
        strokeWidth={1}
        strokeLinejoin="round"
        vectorEffect="non-scaling-stroke"
      />
      <g aria-hidden="true">
        {regions.map((r) => {
          const s = regionStyle(r);
          return (
            <path
              key={r.name}
              data-region
              d={r.d}
              className={s.hosted ? "fill-rr-cyan stroke-rr-cyan" : "fill-rr-violet stroke-rr-violet"}
              fillOpacity={s.fill}
              strokeOpacity={s.stroke}
              strokeWidth={1}
              strokeLinejoin="round"
              vectorEffect="non-scaling-stroke"
            />
          );
        })}
      </g>
      <g aria-hidden="true">
        {pins.map((e) =>
          e.kind === "race" && e.status === "held" ? (
            <circle key={e.id} data-glow={e.id} cx={e.x} cy={e.y} r={rGlow} fill={`url(#${glowId})`} />
          ) : null,
        )}
      </g>
      <g aria-hidden="true">
        {pins.map((e) => {
          const isNext = e === next;
          const hollow = !isNext && (!e.verified || e.status !== "held");
          const label = labels.get(e.id);
          const color = isNext ? violet : "currentColor";
          const r = isNext ? rNext : rPin;
          return (
            <g key={e.id} data-pin={e.id} transform={`translate(${e.x} ${e.y})`}>
              {isNext && (
                <g data-pulse-wrap>
                  <circle
                    data-pulse
                    r={R.pulseFrom * 1.8 * k}
                    fill="none"
                    stroke={violet}
                    strokeWidth={2}
                    opacity={0.5}
                    vectorEffect="non-scaling-stroke"
                  />
                </g>
              )}
              {hollow ? (
                <circle data-dot r={r} fill="none" stroke={color} strokeWidth={1.25} vectorEffect="non-scaling-stroke" />
              ) : (
                <circle data-dot r={r} fill={color} />
              )}
              {label && (
                <text
                  data-label
                  x={label.x - e.x}
                  y={label.y - e.y}
                  textAnchor={label.anchor}
                  dominantBaseline="middle"
                  fontSize={FONT.label}
                  fill="currentColor"
                  fillOpacity={0.85}
                  className="hidden font-mono md:block"
                >
                  {label.text}
                </text>
              )}
            </g>
          );
        })}
      </g>
    </svg>
  );

  const header = (
    <div className={overlay ? "absolute left-0 top-0 w-[27.5%]" : ""}>
      <p className="mb-4 flex items-center gap-2 font-mono text-small text-text-on-ink-muted">
        <span aria-hidden="true" className="h-1 w-1 bg-text-on-ink" />
        <span>05</span>
        <span aria-hidden="true">/</span>
        <span>Community</span>
      </p>
      <h2 id="community-title" className="font-display text-display-l font-semibold text-text-on-ink">
        Teams from around the world
      </h2>
      <p className="mt-5 max-w-[38ch] text-lead text-text-on-ink-muted">
        From Pittsburgh to Busan, students build and race the same open-source car.
      </p>
      <p ref={flashRef} className="mt-4 min-h-[1.5em] font-mono text-small text-text-on-ink-muted" aria-live="off">
        {finalFlash}
      </p>
    </div>
  );

  const counters = (
    <div
      className={
        overlay
          ? "absolute bottom-0 left-0 flex items-end gap-x-8"
          : "grid grid-cols-2 gap-x-6 gap-y-8 border-t border-text-on-ink/15 pt-6 md:border-0 md:pt-0"
      }
    >
      {STATS.map((s, j) => (
        <StatCounter
          key={s.label}
          ref={statRefs.current[j]}
          value={s.value}
          suffix={s.suffix}
          label={s.label}
          on="ink"
          mode="progress"
        />
      ))}
    </div>
  );

  const legend = (
    <ul
      aria-label="Map key"
      className={`flex flex-wrap items-center gap-x-6 gap-y-2 font-mono text-small text-text-on-ink-muted ${
        overlay ? "absolute bottom-0 right-0" : "md:justify-end"
      }`}
    >
      <li className="flex items-center gap-2">
        <span aria-hidden="true" className="inline-block h-2.5 w-2.5 border border-rr-cyan/85 bg-rr-cyan/60" />
        hosted a race, deeper with more
      </li>
      <li className="flex items-center gap-2">
        <span aria-hidden="true" className="inline-block h-2.5 w-2.5 border border-rr-violet/85 bg-rr-violet/60" />
        partner institutions
      </li>
    </ul>
  );

  const venues = (
    <ul className="sr-only">
      {pins.map((e) => (
        <li key={e.id}>{flashText(e)}</li>
      ))}
    </ul>
  );

  const layout = overlay ? (
    <div className="mx-auto w-full max-w-wide px-6">
      <div className="relative">
        {svg}
        {header}
        {counters}
        {legend}
      </div>
      {venues}
    </div>
  ) : (
    <div className="mx-auto w-full max-w-wide px-6">
      <div className="grid gap-8 md:grid-cols-12 md:items-end md:gap-6">
        <div className="md:col-span-7">{header}</div>
        <div className="order-2 md:order-none md:col-span-5">{counters}</div>
        <div className="order-1 md:order-none md:col-span-12">
          {svg}
          {venues}
        </div>
        <div className="order-3 md:col-span-12">{legend}</div>
      </div>
    </div>
  );

  if (reduced) {
    return (
      <section
        aria-labelledby="community-title"
        data-variant="ink"
        className={`bg-ink-950 py-section text-text-on-ink-muted ${className}`}
      >
        {layout}
      </section>
    );
  }

  return (
    <section aria-labelledby="community-title" data-variant="ink" className={`bg-ink-950 text-text-on-ink-muted ${className}`}>
      <div ref={wrapRef} data-map-chapter style={{ height: `${HEIGHT_VH}vh` }}>
        {/* Centered in the viewport below the fixed nav (68 / 85 px measured). */}
        <div className="sticky top-0 flex min-h-svh flex-col justify-center pb-10 pt-[calc(68px+3rem)] md:pt-[calc(85px+3rem)]">
          {layout}
        </div>
      </div>
    </section>
  );
}
