import { createRef, useEffect, useMemo, useRef, useState, useSyncExternalStore, type RefObject } from "react";
import { loadEventsMap, type EventsMap, type MapCountry, type MapEvent } from "../../lib/data";
import { gsap, useGSAP, MOTION_OK_QUERY, ScrollTrigger } from "../../lib/motion";
import { usePrefersReducedMotion } from "../../hooks/usePrefersReducedMotion";
import StatCounter, { type StatCounterHandle } from "./StatCounter";
// Generated by scripts/build-world-map.mjs (Natural Earth I, 1600x820). Inlined
// so the land path and the pins share one coordinate space.
import worldLandSvg from "../../../public/media/map/world-land.svg?raw";

const LAND_PATH = /\sd="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "";
const VIEWBOX = /viewBox="([^"]+)"/.exec(worldLandSvg)?.[1] ?? "0 0 1600 820";
const [, , VB_W] = VIEWBOX.split(" ").map(Number);

// Scale statements from the content skill (kept until Rahul answers).
const STATS = [
  { value: 90, suffix: "+", label: "universities" },
  { value: 20, suffix: "+", label: "countries" },
  { value: 1000, suffix: "+", label: "publications" },
  { value: 30, suffix: "", label: "competitions held" },
] as const;
// "30 competitions held" until IROS 2026 happens (content skill); the ticker
// never claims more. The source lists 33 race-kind pins that already ran, so
// the count reaches 30 at ICCAS 2025 and holds there while CDC 2025, ICRA 2026,
// IV 2026 and the upcoming pins pop (director, 2026-08-21: honest, keep the cap).
const COMPETITIONS_HELD = 30;

// Pin schedule in chapter progress (0..1 over the 260vh wrapper), landing-v3 section 6.
const HEIGHT_VH = 260;
const COUNTRIES_IN = [0.05, 0.4] as const;
const CODES_OUT = [0.35, 0.42] as const;
const PINS = [0.35, 0.85] as const;
const POP = 0.03;
// Counters start together with the first pins and finish before the hold; a
// visible stagger left the last tile reading "0+" mid-pin (critique).
const STATS_START = 0.36;
const STATS_STAGGER = 0.015;
const STATS_DURATION = 0.45;

// Geometry in viewBox units (1600 wide). Desktop renders the map at about
// 826 px (7 columns plus the left page gutter), so 7 units is a 3.6 px dot; on
// mobile everything doubles.
const R = { pin: 7, next: 8, country: 10, pulseFrom: 8, pulseTo: 38 } as const;
const FONT = { label: 22, code: 20 } as const;
const LABEL_GAP = 6;
// Labels the director checks at 1440 (Anchorage, Abu Dhabi, Rio, Jeju, Vienna,
// Pittsburgh) get first pick of the free space.
const LABEL_PRIORITY = ["iv2023", "iros2024", "cdc2025", "iv2024", "icra2026", "iros2026"];

const DESKTOP_QUERY = "(min-width: 768px)";

type Anchor = "start" | "middle" | "end";
type Placed = { x: number; y: number; anchor: Anchor; text: string };
type Box = { x1: number; y1: number; x2: number; y2: number };

function useMatchMedia(query: string): boolean {
  return useSyncExternalStore(
    (onChange) => {
      const mql = window.matchMedia(query);
      mql.addEventListener("change", onChange);
      return () => mql.removeEventListener("change", onChange);
    },
    () => window.matchMedia(query).matches,
    () => true,
  );
}

function ordinal(n: number): string {
  const s = ["th", "st", "nd", "rd"];
  const v = n % 100;
  return `${n}${s[(v - 20) % 10] || s[v] || s[0]}`;
}

function overlaps(a: Box, b: Box): boolean {
  return a.x1 < b.x2 && a.x2 > b.x1 && a.y1 < b.y2 && a.y2 > b.y1;
}

function textBox(x: number, y: number, anchor: Anchor, text: string, fs: number): Box {
  const w = text.length * fs * 0.62;
  const x1 = anchor === "start" ? x : anchor === "end" ? x - w : x - w / 2;
  return { x1, y1: y - fs / 2, x2: x1 + w, y2: y + fs / 2 };
}

/**
 * Greedy label placement in viewBox units: one label per city, tried right /
 * left / above / below the pin, dropped when it would cross a pin or a placed
 * label. A labelDx/labelDy from the source file is a forced position.
 */
function placeLabels(pins: MapEvent[], r: number, fs: number): Map<string, Placed> {
  const placed = new Map<string, Placed>();
  const taken: Box[] = pins.map((p) => ({ x1: p.x - r, y1: p.y - r, x2: p.x + r, y2: p.y + r }));
  // Verified cities first (sanity set, then the upcoming races, then in
  // order); unverified pins come last so they can only add a "tbc" tag to a
  // city a verified race already labelled.
  const rank = (e: MapEvent) => {
    const i = LABEL_PRIORITY.indexOf(e.id);
    if (i >= 0) return i;
    if (!e.verified) return 1000 + pins.indexOf(e);
    if (e.status === "upcoming") return 100;
    return 200 + pins.indexOf(e);
  };
  const labelledCities = new Set<string>();
  const candidates = [...pins].sort((a, b) => rank(a) - rank(b));
  for (const e of candidates) {
    const cityDone = labelledCities.has(e.city);
    if (cityDone && e.verified) continue;
    const verifiedHere = pins.some((p) => p.verified && p.city === e.city);
    const text = e.verified ? e.city : cityDone || verifiedHere ? "tbc" : `${e.city} · tbc`;
    const forcedAnchor: Anchor = e.labelDx === 0 ? "middle" : (e.labelDx ?? 1) < 0 ? "end" : "start";
    const tries: Array<[number, number, Anchor]> =
      e.labelDx !== undefined || e.labelDy !== undefined
        ? [[e.x + (e.labelDx ?? r + LABEL_GAP), e.y + (e.labelDy ?? 0), forcedAnchor]]
        : [
            [e.x + r + LABEL_GAP, e.y, "start"],
            [e.x - r - LABEL_GAP, e.y, "end"],
            [e.x, e.y - r - fs * 0.7, "middle"],
            [e.x, e.y + r + fs * 0.7, "middle"],
          ];
    const forced = tries.length === 1;
    for (const [x, y, anchor] of tries) {
      const box = textBox(x, y, anchor, text, fs);
      const inside = box.x1 >= 0 && box.x2 <= VB_W;
      if (forced || (inside && !taken.some((t) => overlaps(t, box)))) {
        taken.push(box);
        placed.set(e.id, { x, y, anchor, text });
        labelledCities.add(e.city);
        break;
      }
    }
  }
  return placed;
}

/** Country codes (phase 1) use the same rule against the other discs and codes. */
function placeCodes(countries: MapCountry[], r: number, fs: number): Map<string, Placed> {
  const placed = new Map<string, Placed>();
  const taken: Box[] = countries.map((c) => ({ x1: c.x - r, y1: c.y - r, x2: c.x + r, y2: c.y + r }));
  for (const c of countries) {
    const tries: Array<[number, number, Anchor]> = [
      [c.x + r + LABEL_GAP, c.y, "start"],
      [c.x - r - LABEL_GAP, c.y, "end"],
      [c.x, c.y - r - fs * 0.7, "middle"],
      [c.x, c.y + r + fs * 0.7, "middle"],
    ];
    for (const [x, y, anchor] of tries) {
      const box = textBox(x, y, anchor, c.iso2, fs);
      if (box.x1 >= 0 && box.x2 <= VB_W && !taken.some((t) => overlaps(t, box))) {
        taken.push(box);
        placed.set(c.iso2, { x, y, anchor, text: c.iso2 });
        break;
      }
    }
  }
  return placed;
}

function flashText(e: MapEvent): string {
  const tags = [e.label, e.city];
  if (e.status === "upcoming") tags.push("upcoming");
  else if (e.status === "virtual") tags.push("virtual");
  if (!e.verified) tags.push("tbc");
  return tags.join(" · ");
}

type WorldMapChapterProps = {
  className?: string;
};

/**
 * Landing section 05 / Community (serves the sponsor and the press, audiences
 * skill): a pinned ink chapter. Phase 1 lights the partner / team countries,
 * phase 2 pops every competition venue in chronological order while a mono
 * ticker counts them and the four scale numbers count up, phase 3 holds with
 * IROS 2026 pulsing as the only violet element. Reduced motion and no-JS get
 * the final state: every pin, every number, no pin.
 */
export default function WorldMapChapter({ className = "" }: WorldMapChapterProps) {
  const wrapRef = useRef<HTMLDivElement>(null);
  const countRef = useRef<HTMLSpanElement>(null);
  const flashRef = useRef<HTMLParagraphElement>(null);
  const counterBlockRef = useRef<HTMLDivElement>(null);
  const statRefs = useRef<RefObject<StatCounterHandle | null>[]>(STATS.map(() => createRef<StatCounterHandle>()));
  const reduced = usePrefersReducedMotion();
  const desktop = useMatchMedia(DESKTOP_QUERY);
  const [data, setData] = useState<EventsMap | null>(null);

  useEffect(() => {
    let live = true;
    loadEventsMap()
      .then((d) => {
        if (live) setData(d);
      })
      .catch(() => {
        if (live) setData(null);
      });
    return () => {
      live = false;
    };
  }, []);

  // Mobile renders the map at a quarter of the desktop width: double the marks.
  const k = desktop ? 1 : 2;
  const rPin = R.pin * k;
  const rNext = R.next * k;
  const rCountry = R.country * k;

  const pins = useMemo(
    () => (data?.events ?? []).filter((e) => !(e.lat === 0 && e.lng === 0)),
    [data],
  );
  const countries = useMemo(() => data?.countries ?? [], [data]);
  const next = useMemo(() => [...pins].reverse().find((e) => e.status === "upcoming"), [pins]);
  const labels = useMemo(() => placeLabels(pins, rPin, FONT.label), [pins, rPin]);
  const codes = useMemo(() => placeCodes(countries, rCountry, FONT.code), [countries, rCountry]);
  // Running count of competitions (kind "race") that already took place, per pin.
  const heldBefore = useMemo(() => {
    let n = 0;
    return pins.map((e) => {
      if (e.kind === "race" && e.status !== "upcoming") n += 1;
      return n;
    });
  }, [pins]);

  const finalCount = next?.number
    ? ordinal(next.number)
    : String(Math.min(heldBefore[heldBefore.length - 1] ?? 0, COMPETITIONS_HELD));
  const finalFlash = next ? `coming up · ${next.city}` : "";

  useGSAP(
    (_context, contextSafe) => {
      const wrap = wrapRef.current;
      if (!wrap || reduced || pins.length === 0) return;
      const mm = gsap.matchMedia();
      mm.add(MOTION_OK_QUERY, () => {
        const countryGroups = gsap.utils.toArray<SVGGElement>("[data-country]", wrap);
        const codeEls = gsap.utils.toArray<SVGTextElement>("[data-code]", wrap);
        const pinEls = gsap.utils.toArray<SVGGElement>("[data-pin]", wrap);
        const pulseWrap = wrap.querySelector<SVGGElement>("[data-pulse-wrap]");
        const pulse = wrap.querySelector<SVGCircleElement>("[data-pulse]");
        const countEl = countRef.current;
        const flashEl = flashRef.current;
        const block = counterBlockRef.current;

        const pinStep = (PINS[1] - PINS[0] - POP) / Math.max(pinEls.length - 1, 1);
        let lastIndex = -2;
        const flash = contextSafe?.(() => {
          if (flashEl) gsap.fromTo(flashEl, { opacity: 0.25 }, { opacity: 1, duration: 0.35, overwrite: true });
        });

        const tl = gsap.timeline({
          scrollTrigger: {
            trigger: wrap,
            start: "top top",
            end: "bottom bottom",
            scrub: 0.6,
            onToggle: (self) => pulseTween.paused(!self.isActive),
          },
          onUpdate: () => update(tl.progress()),
        });
        const update = (p: number) => {
          {
            // Ticker: the latest pin whose pop is half way.
            const i = Math.min(Math.floor((p - PINS[0] - POP / 2) / pinStep), pinEls.length - 1);
            if (i !== lastIndex) {
              lastIndex = i;
              const e = pins[i];
              if (countEl && flashEl) {
                if (i < 0) {
                  // Non-breaking space keeps the block's height: no column jump.
                  countEl.textContent = " ";
                  flashEl.textContent = " ";
                } else if (e === next && next.number) {
                  countEl.textContent = ordinal(next.number);
                  flashEl.textContent = `coming up · ${next.city}`;
                  flash?.();
                } else {
                  countEl.textContent = String(Math.min(Math.max(heldBefore[i], 1), COMPETITIONS_HELD));
                  flashEl.textContent = flashText(e);
                  flash?.();
                }
              }
            }
            statRefs.current.forEach((ref, j) => {
              ref.current?.setProgress((p - STATS_START - j * STATS_STAGGER) / STATS_DURATION);
            });
          }
        };
        // The markup carries the final state (reduced motion / no JS); the
        // pinned run starts from phase 0 the moment the timeline exists.
        update(0);

        // Phase 1: countries fade in, codes leave as the pins start.
        const countryStagger = (COUNTRIES_IN[1] - COUNTRIES_IN[0] - 0.06) / Math.max(countryGroups.length - 1, 1);
        if (countryGroups.length) {
          tl.fromTo(countryGroups, { opacity: 0 }, { opacity: 1, duration: 0.06, stagger: countryStagger, ease: "none" }, COUNTRIES_IN[0]);
        }
        if (codeEls.length) {
          tl.fromTo(codeEls, { opacity: 0 }, { opacity: 1, duration: 0.06, stagger: countryStagger, ease: "none" }, COUNTRIES_IN[0]);
          tl.to(codeEls, { opacity: 0, duration: CODES_OUT[1] - CODES_OUT[0], ease: "none" }, CODES_OUT[0]);
        }

        // Phase 2: pins pop in array (chronological) order, labels follow.
        if (block) tl.fromTo(block, { opacity: 0 }, { opacity: 1, duration: 0.04, ease: "none" }, PINS[0] - 0.02);
        pinEls.forEach((g, i) => {
          const t = PINS[0] + i * pinStep;
          const dot = g.querySelector<SVGCircleElement>("[data-dot]");
          const label = g.querySelector<SVGTextElement>("[data-label]");
          if (dot) {
            const r = Number(dot.getAttribute("r"));
            tl.fromTo(dot, { attr: { r: 0 } }, { attr: { r }, duration: POP, ease: "back.out(1.6)" }, t);
          }
          if (label) tl.fromTo(label, { opacity: 0 }, { opacity: 1, duration: POP, ease: "none" }, t + POP / 2);
        });
        if (pulseWrap) {
          // Hidden from creation (a zero-duration set at position 0 does not
          // render at progress 0); revealed once the last pin has landed.
          gsap.set(pulseWrap, { autoAlpha: 0 });
          tl.set(pulseWrap, { autoAlpha: 1 }, PINS[1] + 0.005);
        }
        // Phase 3: hold. The next-race ring pulses on its own clock.
        const pulseTween = pulse
          ? gsap.fromTo(
              pulse,
              { attr: { r: R.pulseFrom * k }, opacity: 0.8 },
              { attr: { r: R.pulseTo * k }, opacity: 0, duration: 2.4, repeat: -1, ease: "power1.out", paused: true },
            )
          : gsap.to({}, { duration: 0 });

        wrap.dataset.mapReady = "1";
      });
      document.fonts?.ready?.then(() => ScrollTrigger.refresh());
    },
    { scope: wrapRef, dependencies: [pins, reduced, k], revertOnUpdate: true },
  );

  const violet = "var(--color-rr-violet)";

  // The map bleeds into the left page gutter (-ml-6) so the SVG reaches 826 px
  // at 1440 (7 of 12 columns alone stop at 795): the chapter's visual, not a
  // thumbnail (director, 2026-08-21).
  const map = (
    <div className="order-first md:col-span-7 md:-ml-6">
      <svg
        viewBox={VIEWBOX}
        className="block h-auto w-full text-text-on-ink"
        role="img"
        aria-labelledby="community-map-title"
        aria-describedby="community-map-desc"
      >
        <title id="community-map-title">World map of RoboRacer competition venues since 2016</title>
        <desc id="community-map-desc">
          Soft discs mark partner and team countries; dots mark every competition venue, hollow when the race ran
          online or the venue is still to be confirmed. The violet dot is the next competition.
        </desc>
        <path
          d={LAND_PATH}
          fill="currentColor"
          fillOpacity={0.14}
          stroke="currentColor"
          strokeOpacity={0.28}
          strokeWidth={0.8}
          strokeLinejoin="round"
          vectorEffect="non-scaling-stroke"
        />
        <g aria-hidden="true">
          {countries.map((c) => {
            const code = codes.get(c.iso2);
            return (
              <g key={c.iso2} data-country transform={`translate(${c.x} ${c.y})`}>
                {c.verified ? (
                  <circle r={rCountry} fill="currentColor" fillOpacity={0.35} />
                ) : (
                  <circle r={rCountry} fill="none" stroke="currentColor" strokeOpacity={0.5} strokeWidth={1} vectorEffect="non-scaling-stroke" />
                )}
                {code && (
                  <text
                    data-code
                    x={code.x - c.x}
                    y={code.y - c.y}
                    textAnchor={code.anchor}
                    dominantBaseline="middle"
                    fontSize={FONT.code}
                    fill="currentColor"
                    fillOpacity={0.7}
                    className="hidden font-mono md:block"
                    style={{ opacity: 0 }}
                  >
                    {code.text}
                  </text>
                )}
              </g>
            );
          })}
        </g>
        <g aria-hidden="true">
          {pins.map((e) => {
            const isNext = e === next;
            const hollow = !e.verified || e.status === "virtual";
            const label = labels.get(e.id);
            const color = isNext ? violet : "currentColor";
            const r = isNext ? rNext : rPin;
            return (
              <g key={e.id} data-pin transform={`translate(${e.x} ${e.y})`}>
                {isNext && (
                  <g data-pulse-wrap>
                    <circle
                      data-pulse
                      r={R.pulseFrom * 1.8 * k}
                      fill="none"
                      stroke={violet}
                      strokeWidth={2}
                      opacity={0.5}
                      vectorEffect="non-scaling-stroke"
                    />
                  </g>
                )}
                {hollow ? (
                  <circle data-dot r={r} fill="none" stroke={color} strokeWidth={1.25} vectorEffect="non-scaling-stroke" />
                ) : (
                  <circle data-dot r={r} fill={color} />
                )}
                {label && (
                  <text
                    data-label
                    x={label.x - e.x}
                    y={label.y - e.y}
                    textAnchor={label.anchor}
                    dominantBaseline="middle"
                    fontSize={FONT.label}
                    fill="currentColor"
                    fillOpacity={0.85}
                    className="hidden font-mono md:block"
                  >
                    {label.text}
                  </text>
                )}
              </g>
            );
          })}
        </g>
      </svg>
      <ul className="sr-only">
        {pins.map((e) => (
          <li key={e.id}>{flashText(e)}</li>
        ))}
      </ul>
    </div>
  );

  const column = (
    <div className="md:col-span-5">
      <p className="mb-4 flex items-center gap-2 font-mono text-small text-text-on-ink-muted">
        <span aria-hidden="true" className="h-1 w-1 bg-text-on-ink" />
        <span>05</span>
        <span aria-hidden="true">/</span>
        <span>Community</span>
      </p>
      <h2 id="community-title" className="font-display text-display-l font-semibold text-text-on-ink">
        Teams from around the world
      </h2>
      <div ref={counterBlockRef} className="mt-8" aria-live="off">
        <p className="min-h-[1em] font-mono text-display-xl font-semibold leading-none tabular-nums text-text-on-ink">
          <span ref={countRef}>{finalCount}</span>
        </p>
        <p ref={flashRef} className="mt-2 min-h-[1.5em] font-mono text-small text-text-on-ink-muted">
          {finalFlash}
        </p>
      </div>
      <div className="mt-8 grid grid-cols-2 gap-x-6 gap-y-8 border-t border-text-on-ink/15 pt-6">
        {STATS.map((s, j) => (
          <StatCounter
            key={s.label}
            ref={statRefs.current[j]}
            value={s.value}
            suffix={s.suffix}
            label={s.label}
            on="ink"
            mode="progress"
          />
        ))}
      </div>
    </div>
  );

  const grid = (
    <div className="mx-auto w-full max-w-wide px-6">
      <div className="grid gap-10 md:grid-cols-12 md:items-center md:gap-x-6">
        {column}
        {map}
      </div>
    </div>
  );

  if (reduced) {
    return (
      <section
        aria-labelledby="community-title"
        data-variant="ink"
        className={`bg-ink-900 py-section text-text-on-ink-muted ${className}`}
      >
        {grid}
      </section>
    );
  }

  return (
    <section aria-labelledby="community-title" data-variant="ink" className={`bg-ink-900 text-text-on-ink-muted ${className}`}>
      <div ref={wrapRef} data-map-chapter style={{ height: `${HEIGHT_VH}vh` }}>
        {/* Centered in the viewport below the fixed nav (68 / 85 px measured). */}
        <div className="sticky top-0 flex min-h-svh flex-col justify-center pb-12 pt-[calc(68px+3rem)] md:pt-[calc(85px+3rem)]">
          {grid}
        </div>
      </div>
    </section>
  );
}
